---
title: x86
tags: x86, architecture
category: x86
description: Introduction to the x86 CPU architecture.
---

*x86* is a backwards compatible family of little-endian, complex instruction
set architectures (ISA) introduced in 1978 by Intel.
The two preeminent manufacturers of CPUs implementing x86 are Intel and AMD.
The iterations of the ISA can be broadly classified by integer width:

* 16-bit x86, also referred to as *IA-16*, *x86-16* or *x86_16* (introduced
  with the Intel 8086 in 1978).
* 32-bit x86, also referred to as *IA-32*, *x86-32* or *x86_32* (introduced
  with the Intel 386 in 1985).
* 64-bit x86 (not to be confused with IA-64), also referred to as *x86-64*,
  *x86_64*, *AMD64* or *x64*.
  It is also referred to as _EM64T_, _IA-32e_ or _Intel64_ by Intel.

== History
=== First generation
The first iteration of the x86 architecture was introduced in 1978 with the
*Intel 8086*.
The 8086 is a 16-bit CPU, with 16-bit registers, a 16-bit data bus and a 20-bit
address bus.
Thus it is able to address one megabyte of RAM.
Although the 8086 has no binary compatibility with the 8080 or 8085, the design
is such, that all 8080 or 8085 programs could be machine translated to work on
the 8086.

Slightly later, the *Intel 8088* CPU was introduced, which is internally
identical to the 8086, but had a 8-bit data bus.
The 8088 is used by the original IBM PC, introduced in 1981, which is the
predecessor of all modern PCs.
Thus, the x86 architecture became the dominant architecture on personal
computers.

Intel also introduced the *Intel 8087* FPU that provides floating-point
capabilities, and operates in parallel to the main processor.
The Intel 8089 IOP (I/O processor) was also introduced to allow fast I/O
operations without CPU supervision, allowing for an increasing degree of
parallelism.
However, the IBM PC does not use the 8089, instead using the simpler Intel 8237
(designed for the 8-bit 8085).
This meant that no successor to the 8089 was ever made.

=== Second generation
In 1982, Intel introduced the *Intel 80186*, *Intel 80188* and *Intel 80286*
(also known as the 186, 188 and 286 respectively).
The 186 and 188 are similar to the 8086 and 8088 respectively, but are intended
for embedded systems, and integrate peripherals that are not compatible with
IBM PCs.

Although the 8087 is compatible with both the 186 and 187, the *Intel 80187*
(also known as the 187) was introduced much later as a math coprocessor
compatible the 186 (but not the 188).
The 187 is internally more similar to the 387 and supports all the 387
instructions and was IEEE 754 compliant.

The 286, however, is intended for multi-user, multitasking environments.
Thus the 286 introduced features for multitasking and memory protection and was
able to address up to 16 MiBs of RAM.
To preserve compatibility with the 8086, most of the features introduced with
the 286 can only be used in a mode called _protected mode_.
The 286 and most subsequent x86 processors start in _real mode_, which emulates
the behavior of a 8086.
The 286 started to gain wide adoption with the introduction of the IBM AT in
1984.

The math coprocessor for the 286 is the *Intel 80287* (also known as the 287).
A later version of the 287, known as the 287XL, is internally similar to the
387SX.
The 287 is also compatible with the 386DX and 386SX.

=== NEC V20
The *NEC V20* is a pin compatible replacement for the 8088, that was a very
popular upgrade for XT-class machines, due to being able to execute more
instructions on average in a smaller amount of time.
Variants include the *NEC V30*, which is pin compatible with the 8086, the
_NEC V40_, which corresponds to the 188, and the _NEC V50_, which corresponds
to the 186.
The _NEC V33_ and its variant, the _NEC V53_, is a V30 variant with performance
equivalent to a 286 and can address up to 16 MiB of memory.
The _NEC V25_ and _NEC V35_ are microcontroller variants of the V20 and V30
respectively.
The later V60 series implements a different ISA, but has a V20 emulation mode.

All these CPUs support the 186 instruction set and new instructions exclusively
available on NEC CPUs.
Among other things, these instructions include nibble and bitwise operations.
The V25 and V35 implement additional enhancements, such as eight register banks
for interrupt handling.

In addition to the enhancements common to all V-series CPUs, the V20, V30, V40
and V50 feature an _8080 emulation mode_, whereby 8080 binaries can be executed
without translation.

The V33 and V53 implement _expanded addressing mode_, which allows the use of
up to 16 MiB of RAM.
This mode is essentially real mode with paging of 16 kiB pages.
The translation table translating the 20-bit linear address to a 24-bit
physical address is mapped to the I/O ports 0xFF00 to 0xFF7F.

=== Third generation
In 1985, Intel introduced the *Intel 386DX*.
This new iteration introduced support for 32-bit integers and extended
protected mode to introduce, among other things, paging and support for up to
4 GiBs of RAM.
Later, Intel introduced the *Intel 386SX*, which is internally similar to the
386DX, but has a 16-bit data bus and 24-bit address bus, rather than 32-bit
busses.

In 1987, the *Intel 387DX* was introduced.
Due to its 32-bit data bus, it is incompatible with the 386SX, which has its
own math coprocessor called the *387SX*

=== Fourth generation
In 1989, the *Intel 486DX* was introduced, introducing new features, such as
tightly coupled (i.e. true) pipelining and an integrated FPU.
The *Intel 486SX* variant is a version without an integrated FPU.footnote:[Early
486SX chips are actually 486DX chips with the FPU disabled.]
A *Intel 487SX* math coprocessor upgrade was available for 486SX systems.footnote:[The
487SX is actually a full 486DX that disabled the 486SX completely.]

=== Fifth generation
In 1993, the *Intel Pentium* was introduced, featuring the new *P5* (also known
as *i586*) microarchitecture, which introduced superscalar architecture, a
64-bit external data bus and branch prediction.

=== Sixth generation
The Pentium was followed up by the Pentium Pro in 1995, which is the first
implementation of the *P6* (also known as *i686*) microarchitecture,
introducing register renaming, out-of-order execution, speculative execution
and a 36-bit address bus, that allowed for up to 64 GiBs of RAM, that could be
accessed through PAE or PSE-36.

Intel's competitors also started building their chips on their own, unique,
in-house designs, such as the AMD K5 (introduced in 1996) and the Cyrix 5x86
(1995) and 6x86 (1996), rather than trying to replicate Intel's chips, or
orient their designs around them, as with the Am486 and Am5x86 and the Cx486.

=== x86-64
The first processor to implement *x86-64*, a 64-bit extension originally
proposed by AMD in 1999, was the AMD Opteron, introduced in 2003.
Aside from increasing the size and count of general-purpose and SSE registers,
it introduced 64-bit linear addresses, albeit the paging scheme restricts the
virtual address space to 48 bits (splitting it into to halves through sign
extension).
In addition, many legacy features, such as certain aspects of segmentation,
have been removed.
To maintain backwards compatibility these new features can only be used in
long mode.
The behavior compatible with older CPUs (i.e. real and protected mode) are
available in legacy mode.

To this day, every properly-implemented x86 processor has a large degree of
binary backwards compatibility, all the way back to the original Intel 8086.

== Operating modes
x86 has a handful of operating modes.
On x86-64 processors, real mode and protected mode are grouped together into
_legacy mode_.

=== Real mode
*Real mode* is the operating mode that an x86 processor boots into.
It mostly models the original 16-bit 8086 processor, with a few extensions.
Real mode contains no access rings or memory protection of any kind.

Access to memory is done via a 16-bit _segment address_ and a 16-bit _offset_,
using following formula:

[source]
physical_address = segment * 16 + offset

The default operand and address size is 16-bit.
The segment limit is 65536 bytes (64 kiB), this means even when using a 32-bit
address size prefix, the offset may not exceed 65535.

Due to these limitations, software in real mode can only directly access the
first 1114096 (1 MiB + 64 kiB - 16 bytes) of physical memory:

[source]
65535 * 16 + 65536 = 1114096

==== Unreal mode
_Unreal mode_, also known as _flat real mode_, _32-bit real mode_ or
_voodoo mode_, is an originally undocumented variant of real mode that alters
the segment descriptor cache, in order to allow 32-bit offsets, so that
programs may access up to 4 GiB of memory.
Unreal mode is available on the 386 and above.

===== Big real mode
_Big real mode_, also known as _big unreal mode_, sets the limit of data
segments to 4 GiB, allowing for a flat 32-bit physical address space
starting from zero, if segment zero is used.

===== Huge real mode
_Huge real mode_, also known as _huge unreal mode_, sets the limit of code
segments to 4 GiB, in addition to changing the data segment limit.
However, the high 16 bits of EIP are not saved by real mode interrupts,
making it difficult to use.

=== Protected mode
*Protected mode* was introduced with the 286 and provides memory protection.
Unlike real mode, there is no linear relationship between segment address and
segment base address.
The segment base address and other properties of each segment are determined by
the _global descriptor table (GDT)_ and _local descriptor table (LDT)_.
The segment address is now a segment selector, which is essentially an index
to a segment descriptor.

Protected mode provides four protection rings, Ring 0 being the most privileged
and Ring 3 being the least privileged.
Most operating systems only use Ring 0 and Ring 3.
Code running in Ring 0 may access any segment and may interface directly with
hardware.
The privileges of other Rings depend on the GDT and LDT and the state of the
CPU.
Ring 0 is often referred to as "kernel mode" and Ring 3 is often referred to as
"user mode".

The 286 allows for up to 16 MiB of RAM, however extensions to protected mode
introduced with the 386 increase this to 4 GiB.
The 386 also introduced optional paging to protected mode, allowing for an
extra level of translation after segmentation.
Later extensions, such as PAE and PSE-36, increase the maximum size of physical
memory to beyond 4 GiB.
However, the size of virtual address space is still limited to 4 GiB.

Thus, the _logical address_, consisting of segment selector and offset is first
translated to a _linear address_, by adding the segment base address of the
corresponding segment descriptor to the offset.
If paging is enabled, the linear address is translated to a _physical address_,
otherwise the linear address corresponds to the physical address.

Protected mode has two sub-modes, depending on the current code segment.
However, 16-bit and 32-bit segment descriptors may coexist in the same
descriptor table.

==== 16-bit protected mode
If the current code segment is a 16-bit segment, the default address and
operand size is 16-bit.

Code targeting real mode is largely compatible with 16-bit protected mode,
assuming, among other things, it does not attempt to do any privileged
operation, does not assume that there is a direct relationship between segment
base and segment address (as is the case in real mode) and does not try to
modify code or execute data.
In practice, most existing real mode programs do at least one of the things
listed above, rendering them incompatible with 16-bit protected mode.

==== 32-bit protected mode
If the current code segment is a 32-bit segment, the default address and
operand size is 32-bit.

32-bit addressing allows for up to 4 GiB of directly addressable RAM, rather
than 64 kiB, as is the case with 16-bit addressing.
This, along with paging, largely removes the necessity for multiple segments,
as modern operating systems mostly rely on paging and have one code segment and
one data segment per ring per virtual address space, usually having the base
zero.
To a 32-bit user program, segmentation is essentially transparent and the
address space consists of 4 GiB of flat, contiguous memory.

==== Virtual 8086 mode
_Virtual 8086 mode_ was introduced with the 386 and allows the execution of
real mode programs in a virtual machine under a hypervisor in protected mode.

=== System management mode
Introduced with the 386SL (a CPU targeting laptops), *system management mode*
is mostly transparent to the operating system.
System management mode is intended for firmware to provide functions, such as
power management, independently from the operating system that is currently
running.

=== Long mode
*Long mode* was introduced with x86-64 and allows software to use 64-bit
address and data.
Linear addresses are now 64-bit, thus allowing for a virtual address space of
up to 16 EiB.
The paging scheme restricts this to 48-bit, however, with the remaining bits
being sign extended, thus producing two halves of 128 TiB of "canonical address
space".
An address that complies with this sign extension requirement is said to be in
_canonical form_.
The half starting at zero is called the (canonical) _lower half_.
The half starting at 16 EiB - 128 TiB is called the (canonical) _higher half_.

If 5-level paging (also known as LA57) is enabled, the canonical address space
is extended to 57-bit, thus extending the maximum amount of virtual memory from
256 TiB to 128 PiB.

Much like protected mode, long mode has three sub-modes depending on the
current code segment.

==== 64-bit mode
If the current code segment is 64-bit, the code is interpreted as 64-bit code
and 64-bit registers may be used.
Many legacy features of protected mode, such as segmentation, are largely
disabled.
CS, DS, ES and SS always have base zero, while FS and GS may have
a non-zero base.
No segment limit checks are performed.

==== Compatibility mode
_Compatibility mode_ (not to be confused with legacy mode), is a sub-mode of
long mode, that allows 16-bit and 32-bit applications to run alongside 64-bit
applications.
Segmentation works like in protected mode, but many features only directly
visible to the operating system, such as paging, system calls and interrupts
work as they do in 64-bit mode.

Certain features, such as virtual 8086 protected mode, no longer work under
compatibility mode.

===== 16-bit compatibility mode
If the current code segment is 16-bit, the code will be interpreted as 16-bit
code.
As with 16-bit protected mode, most existing real mode software cannot be run
in 16-bit compatibility mode.

===== 32-bit compatibility mode
If the current code segment is 32-bit, the code will be interpreted as 32-bit
code.
32-bit compatibility mode allows existing 32-bit programs to be run under long
mode.

==== x86 virtualization
Modern x86 processors provide hardware-assisted virtualization.
Intel processors have *VT-x* (also known as VMX) and AMD processors have *AMD-V*
(also known as SVM).

== Instruction set and execution model
Each of the major x86 generations introduce major additions to the core
instruction set.

In the context of x86 a _word_ is a 16-bit value, a _dword_ is a 32-bit value
and a _qword_ is a 64-bit value.footnote:[As is convention elsewhere, a byte is
an 8-bit value and a nibble is a 4-bit value.]

[NOTE]
Cells of tables describing a data structure may be left empty, labeled
"reserved", "0" or "1", in order to indicate this field is reserved.
Software should make no assumption about the value of these fields.
Modifying reserved bits of CPU registers should be avoided.
Memory fields marked as "reserved" should be set to zero.

=== 8086
==== Registers
The 8086 has eight word-sized and eight byte-sized general-purpose registers.
These byte-sized registers are aliases for individual bytes of the word-sized
general-purpose registers AX, BX, CX and DX.
The byte register AL is an alias for the low byte of AX, the byte register AH
is an alias for the high byte of AX.
Analogous relationships exist between BL, BH and BX, CL, CH and CX, and DL, DH
and DX.
The remaining 16-bit general-purpose registers are SI (source index), DI
(destination index), BP (base pointer) and SP (stack pointer).

In addition to the general purpose registers, there are four word-sized segment
registers:
the code segment CS, the data segment DS, the extra segment ES and the
stack segment SS.
There are also two word-sized registers that are only indirectly accessible to
the programmer: the 16-bit instruction pointer IP and the FLAGS register.

.8086 registers
[%collapsible]
====
[%header,cols="6,16*"]
|===
| Register name
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| AX (accumulator) 8+| AH 8+| AL

| CX (counter) 8+| CH 8+| CL

| DX (auxiliary accumulator) 8+| DH 8+| DL

| BX (base address) 8+| BH 8+| BL

| SP (stack pointer) 16+| SP

| BP (base pointer) 16+| BP

| SI (source index) 16+| SI

| DI (destination index) 16+| DI

| IP (instruction pointer) 16+| IP

| FLAGS | 1 | 1 | 1 | 1 | OF | DF | IF | TF | SF | ZF | | AF | | PF | | CF

| ES (extra segment) 16+| ES

| CS (code segment) 16+| CS

| SS (stack segment) 16+| SS

| DS (data segment) 16+| DS
|===
====

The 8086 has following flags:

Carry flag (CF):: Indicates an arithmetic carry for unsigned operations.
Parity flag (PF):: Is set if the parity of the result of an arithmetic
                   operation is even.
Adjust flag (or auxiliary carry flag, AF):: Indicates a carry out of the first
                                             nibble of an arithmetic operation.
Zero flag (ZF):: Is set if the result is zero.
Sign flag (SF):: Indicates a negative value as the result of a signed
                 arithmetic operation.
Trap flag (TF):: If set, interrupt 1 (see below) is raised on each instruction
                 that is executed.
                 The trap flag is automatically cleared when an interrupt is
                 dispatched.
Interrupt flag (IF):: If cleared, all hardware interrupts are disabled, except
                      for NMI.
                      The interrupt flag is automatically cleared when an
                      interrupt is dispatched.
Direction flag (DF):: Determines the direction of string operations.
                      If it is cleared, the indices (SI or DI) involved are
                      increased.
                      If it is set, the indices are decreased.
Overflow flag (OF):: Is set, if a signed arithmetic operation results in an
                     overflow.

==== Instruction modes
Since memory is accessed through a segment address (which is always the value
of one of the segment registers), in addition to an offset (the notation
segment:offset is used), the program counter and stack pointer consist of two
16-bit registers.
The program counter is CS:IP and the stack pointer is SS:SP.

The normal flow of execution is increasing IP.
CS is not automatically incremented, if IP exceeds the limit of CS,
instead IP either wraps around to zero (as is the case on the 8086) or an
exception is raised on later CPUs.

On x86, the stack grows downwards, `push` decreases SP and `pop` increases
SP.
As with the program counter, exceeding the limits of the stack segment does not
result in a change in SS.

Despite having eight general-purpose registers, the 8086 instruction set is not
very orthogonal.
Every 16-bit register has a special role in at least one instruction, examples
include:

* AL is the 8-bit accumulator and is used to store the quotient of a
  `div byte` instruction.
* AH is used to store the remainder of a `div byte` instruction.
* AX is used to store the quotient of a `div word` instruction.
* BX is used as the table base address for the `xlat` instruction.
* CX is used as a counter for the `loop` instruction.
* DX is used to store the remainder of a `div word` instruction.
* SI is used as the source address for the `movsb` and `movsw` instructions.
* DI is used as the destination address for the `movsb` and `movsw`
  instructions.
* Using BP as the base of the effective address (see below) will result in
  the use of the stack segment.
* SP is the stack pointer.

Every instruction involving memory has a default segment and most may be
overridden using a *segment override prefix*.
Most memory operands may have a wide variety of indirect addressing modes.
Offsets may be determined through a runtime computation of adding up to three
values:

* *base* - either zero, BX or BP
* *index* - either zero, SI or DI
* *displacement* - a constant value (encoding allows either zero, a
  sign-extended byte or a word)

The result of the computation is called the *effective address (EA)* (one may
write `[base + index + displacement]` to refer to the corresponding memory
address, or `[segment:base + index + displacement]` when using a segment
override).
The default segment is DS, except when the base is BP, in which case it is SS.

.8086 addressing modes
|===
| Effective address | Displacement formats | Default segment

| `bx + si + disp` | Zero, byte or word | DS

| `bx + di + disp` | Zero, byte or word | DS

| `bp + si + disp` | Zero, byte or word | SS

| `bp + di + disp` | Zero, byte or word | SS

| `si + disp` | Zero, byte or word | DS

| `di + disp` | Zero, byte or word | DS

| `bp + disp`
| Byte or wordfootnote:[The encoding for displacement zero is used to indicate
  a direct offset.
  This means `[bp\]` is encoded as `[bp+0\]` and is not shorter than `[bp+1\]`
  (e.g. the encoding for `[si+0\]` is shorter than `[si+1\]`).]
| SS

| `disp` footnote:[As in: direct memory reference.] | Word | DS

| `di + disp` | Zero, byte or word | DS
|===

==== Memory models
Since 16-bit segments are limited to 64 kiB, applications may use multiple
segments, meaning that there are multiple ways to organize a program into
memory segments.
These schemes are called *memory models*.
There are six standard memory models that are widely supported by compilers and
assemblers:

Tiny:: Everything is in a single segment.
Small:: One code segment, one data segment.
Compact:: One code segment, multiple data segments.
Medium:: Multiple code segments, one data segment.
Large:: Multiple code segments, multiple data segments.
Huge:: Single memory range up to 1 MiB (see below).

There exist three types of pointers:
Near pointers:: Word-sized offsets that are used when there is no ambiguity
                regarding the segment.
Far pointers:: Dword-sized segment-offset pairs that are used when there is a
               necessity to specify what segment is used.
Huge pointers:: Similar to far pointers, in that they are dword-sized
                segment-offset pairs, and are used in the huge memory model.

The *huge memory model* takes advantage of the linear relationship between
segment address and segment base in real mode, to treat the entire 1 MiB range
as a single memory segment.
This is done through huge pointers, which are essentially far pointers that are
normalized, so the offset is always smaller than 16.
This effectively yields a 20-bit address, if the highest 12 bits of the offset
are ignored (since they are always zero due to normalization).
This allows the transparent implementation of arrays larger than 64 kiB.
The stack, however, may not exceed 64 kiB.
Due to relying on real mode segment arithmetic, it does not work in protected
mode.

.8086 memory models
|===
| Memory model | Code pointer type | Data pointer type | Segment registers

| Tiny | Near | Near | CS = DS = ES = SS

| Small | Near | Near | DS = SS

| Compact | Near | Far |

| Medium | Far | Near | DS = SS

| Large | Far | Far |

| Huge | Huge | Huge |
|===

==== Interrupts and exceptions
The 8086 supports 256 types of interrupts.
Interrupts may be caused by hardware, by a CPU exception or explicitly by
software through the `int` instruction.
When an interrupt is raised, the processor pushes the current state of the
flags register, current code segment and the offset of the next instruction to
be executed when the interrupted program is resumed.
It then determines the address to jump to using the *interrupt vector table
(IVT)*, a 1 kiB (256 times 4 bytes) table starting at physical address zero,
consisting of far pointers.

The routine that is called when an interrupt happens is called the *interrupt
service routine (ISR)*.
An ISR may resume the interrupted program through the `iret` instruction.
The 8086 generates following CPU exceptions:

* Division by zero (interrupt 0) occurs when a `div` or `idiv` instruction has
  operand zero or if the quotient does not find into the accumulator.
* Single-step trap (interrupt 1) occurs when the trap flag (see above) is set.
* Debug breakpoint (interrupt 3) is invoked when the (single byte) `int3`
  instruction is executed.
* Overflow (interrupt) is invoked when the `into` (interrupt on overflow)
  instruction is executed and the overflow flag is set.

Interrupt 2 is dispatched when a hardware NMI occurs.
Intel reserved the first 32 interrupts for future use (i.e. additional CPU
exceptions).
IBM did not heed that recommendation, causing compatibility issues.

.Near call stack
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp` | Caller stack | Caller stack | `sp + 2`

| `sp - 2` | | `ip` | `sp`
|===
====

.Real mode far call stack
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp` | Caller stack | Caller stack | `sp + 4`

| `sp - 2` .2+| | CS | `sp + 2`

| `sp - 4` | IP | `sp`
|===
====

.Real mode interrupt stack
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp` | Caller stack | Caller stack | `sp + 6`

| `sp - 2` .3+| | FLAGS | `sp + 4`

| `sp - 4` | CS | `sp + 2`

| `sp - 6` | IP | `sp`
|===
====

=== 80186
The 186 and 188 implement all of the new 286 instructions that are not related
to protected mode or the new registers that have been added.
New CPU exceptions, such as the invalid opcode exception, were also introduced.
These extensions consist of:

* immediate modes for `imul`, `push` and the shift and roll instructions
* string operations on I/O ports
* `bound` instruction and the bounds range exceeded exception
* shorthands `enter`, `leave`, `pusha`, `popa`
* invalid opcode and coprocessor not present exceptions

[NOTE]
The 186 and 188 are still very similar to the 8086 and 8088.
No new registers are added and the behavior of `push sp` and `pushf` are the
same as with the 8086.

=== 80286
The introduction of protected mode with the 286 is a major change to the x86
ISA.
Protected mode introduces new data structures, mechanisms for virtual memory,
memory protection and hardware task switching.

Hardware memory protection is primarily enforced through *protection rings*.
Ring 0 is the most privileged and Ring 3 is the least privileged.
Rings with lower number (more privilege) are referred to hereafter as _lower_,
rings with higher number (less privilege) are referred to hereafter as _higher_
(i.e. the numeric relation).

.286 registers
[%collapsible]
====
[%header,cols="3,16*"]
|===
| Register
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| AX (accumulator) 8+| AH 8+| AL

| CX (counter) 8+| CH 8+| CL

| DX (auxiliary accumulator) 8+| DH 8+| DL

| BX (base address) 8+| BH 8+| BL

| SP (stack pointer) 16+| SP

| BP 16+| BP

| SI 16+| SI

| DI 16+| DI

| IP 16+| IP

| FLAGS
| 0 | *NT* 2+| *IOPL* | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| MSW
| 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | *TS* | *EM* | *MP* | *PE*

.4+| ES 16+| ES (visible selector)
8+| _Access byte_ 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.4+| CS 14+| (visible CS selector) 2+| CPL
8+| _Access byte_ 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.4+| SS 14+| (visible SS selector) 2+| CPL
8+| _Access byte_ 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.4+| DS 16+| DS (visible selector)
8+| _Access byte_ 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.4+| TR 16+| TR (visible selector)
8+| 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.4+| LDTR 16+| LDTR (visible selector)
8+| 8+| _Base (23:16)_
16+| _Base (15:0)_
16+| _Limit_

.3+| GDTR 8+| 8+| Base (23:16)
16+| Base (15:0)
16+| Limit

.3+| IDTR 8+| 8+| Base (23:16)
16+| Base (15:0)
16+| Limit
|===
====

==== Segmentation
There is no longer a linear relationship between segment address and segment
base.
Instead, the properties of segments are determined by *segment descriptors*.
The values of the segment registers are now interpreted as *segment selectors*.
The segment selector is essentially an index to one of the two segment
descriptor tables: the *Global Descriptor Table (GDT)* and the *Local
Descriptor Table (LDT)*.

As the names suggest, the GDT contains segment descriptors for every task and
the LDT contains segment descriptors for a specific task.
Thus, each task can access a global virtual address space, in addition to
having its own, private address space.

The IVT is replaced by the *Interrupt Descriptor Table (IDT)*.
The IDT has an identical format to the GDT and LDT, but instead of referring to
entries in the IDT through segment selectors, each entry in the IDT corresponds
to an interrupt type (i.e. the first entry corresponds to interrupt 0, the
second to interrupt 1, and so on), with the descriptor defining the ISR to be
used.

The 286 includes facilities for managing multiple tasks.
The state of a task is stored in a *Task State Segment (TSS)*.
Both LDT and TSS are segments, much regular segments, and have a corresponding
entry in the GDT.

.Segment selector format
[cols="16*"]
|===
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

13+| Index | TI 2+| RPL
|===

Index:: The index within the descriptor table.
TI:: The table indicator. Zero for GDT; one for LDT.
RPL:: The requested privilege level.

Descriptor tables are arrays of 8-byte segment descriptors that reside in
RAM.
The first entry of the GDT is reserved.
Selectors referring to this entry are so-called _null selectors_ and may be
used as placeholder values for DS and ES, but not CS and SS.
Any attempt to access memory through a null selector results in a general
protection fault.
The IDT may only contain task, interrupt or trap gates.

.286 segment descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Reserved

| +32 | P 2+| DPL | S 4+| Type 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

Limit:: The highest allowed offset address (inclusive).
        This means a limit of 65535 indicates a segment of 65536 bytes, a limit
        of zero indicates a segment of one byte.
        For expand-down segments, it is lowest allowed offset address minus one
        (i.e. exclusive), with the maximum allowed offset being 65535.
        A limit of 65535 indicates an empty segment, a limit of zero indicates
        a segment of 65535 bytes.
        If the present bit is not set, this field may be used for other data.
Base:: Physical address of the first byte of the segment (equivalent to offset
       zero).
       For expand-down segments, defines the first byte after the last byte
       of the segment (also effectively equivalent to offset zero).
       If the present bit is not set, this field may be used for other data.
Type:: Meaning depends on the whether it is a system segment descriptor or a
       code or data segment descriptor.
S flag:: Zero for system segment descriptors; one for code or data descriptors.
DPL:: Descriptor privilege level.
Present bit (P):: Zero indicates the segment is invalid (intended for operating
                  systems to implement swapping).

The fifth byte of a descriptor (i.e. the type, S, DPL and P fields) is known as
the *access byte*.

.Code and data segment types
[cols="4*"]
|===
| 43 | 42 | 41 | 40

| X | CE | RW | A
|===

Executable bit (X):: One for code segments; zero for data segments.
Conforming/expand-down bit (CE):: For code segments: zero for nonconforming
                                  code segments; one for conforming code
                                  segments.
                                  For data segments: zero for expand-up data
                                  segments; one for expand-down data segments.
Readable/writable bit (RW):: For code segments: zero for execute-only code
                             segments; one for readable code segments.
                             For data segments: zero for read-only data
                             segments; one for writable data segments.
Accessed bit (A):: This bit is set when a segment is accessed.
                   This way the operating system can keep track of which
                   segments were used.

.286 system segment types
[cols="4*,5,6"]
|===
| 43 | 42 | 41 | 40 | Segment type | Descriptor tables

| 0 | 0 | 0 | 0 | Reserved | None

| 0 | 0 | 0 | 1 | Available TSS | GDT only

| 0 | 0 | 1 | 0 | LDT descriptor | GDT only

| 0 | 0 | 1 | 1 | Busy TSS | GDT only

| 0 | 1 | 0 | 0 | Call gate | All

| 0 | 1 | 0 | 1 | Task gate | GDT, LDT

| 0 | 1 | 1 | 0 | Interrupt gate | IDT only

| 0 | 1 | 1 | 1 | Trap gate | IDT only

| 1 | x | x | x | Reserved | None
|===

Gates have a different format to other segment descriptors (i.e. code, data,
LDT and TSS segments).

.16-bit gate descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Reserved

| +32 | P 2+| DPL | S 4+| Type 3+| Reserved 5+| Word count

| +16 16+| Segment

| +0 16+| Offset
|===

Offset:: Target offset (unused by task gate).
Segment:: Target segment selector.
          Must point to code segment for call, interrupt and trap gates and to
          a TSS for task gates.
          The RPL field is ignored by call, interrupt and trap gates.
Word count:: Amount of words to push.
             Call gates only; reserved for all other kinds of gate.

In addition to the visible 16-bit selectors, all segment registers have an
invisible _segment descriptor cache_,footnote:[This also applies to real mode,
where the 8086 behavior is emulated by updating the base value with the
segment address times 16, instead of looking up a descriptor table.
Other values, such as the limit are constant and are set to initial values,
in order to replicate 8086 behavior.
This means they can be changed by switching to protected mode, loading the
segment registers with new descriptors and back to real mode.
This is what unreal mode is.]
which contains the segment descriptor corresponding to the selector, so that
the CPU does not need to constantly look up the descriptor tables.

The location of the GDT, LDT, IDT and TSS are indicated by the
_GDT Register (GDTR)_, _LDT Register (LDTR)_, _IDT Register (IDTR)_ and
_Task Register (TR)_ respectively.
The LDTR and TR are similar to regular segment registers, as they store a
16-bit selector, visible to the programmer, and a hidden descriptor cache.
The LDTR can be set using the `lldt` instruction and the TR can be set using
the `ltr` instruction.
Both of these instructions accept a 16-bit direct operand (register or
memory) containing selector pointing to the corresponding descriptor in the
GDT.

The GDT and IDT are not segments and the GDTR and LDTR do not have the visible
16-bit selector part.
The GDTR and LDTR are effectively 48-bit registers and may be set using the
`lgdt` and `lidt` instructions respectively, which take a pointer to a 6 byte
structure called a _pseudo-descriptor_ that is similar to a regular segment
descriptor, due to having base and limit fields.

.286 pseudo-descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +32 8+| Reserved 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

==== Memory protection
Protected mode introduces new memory protection mechanisms.
In order to understand these, one must first understand the different privilege
levels that are taken into account:

* The __current privilege level (CPL)_ is the privilege level of the current
  task.
  It corresponds to the RPL field of the segment selectors stored in CS and
  SS (i.e. bits 0 and 1 of the visible 16-bit values of CS and SS).
* The __descriptor privilege level (DPL)__ is the privilege level of the
  segment being accessed (determined in the segment descriptor).
* The __requested privilege level (RPL)__ is the privilege level given by the
  segment selector (i.e. bits 0 and 1 of the segment selector).
* The __effective privilege level (EPL)__ is the maximum of the CPL and RPL.
* The __I/O privilege level (IOPL)__ is a value in the FLAGS register that
  determines the highest CPL allowed to do direct I/O and to set and clear the
  interrupt flag (`cli` and `sti`) within the current task.

Certain instructions, such as `lgdt`, can only be used if the CPL is 0.
There are also forms of protection independent of the privilege levels, such as
checking segment limits, restricting writing a code segment or read-only data
segment, and restricting reading an execute-only code segment through a CS
override.

Before accessing a segment, a segment register must first be set.
This CPU means the can perform most privilege checks at that point, instead of
every time memory is read or written.
The particular privilege level checks depends on how the segment register is
set and the type of descriptor the selector points to.

DS, ES and SS can be changed directly through `mov` and `pop`.
In general, these registers must be loaded with data segments or readable code
segments with the DPL higher or equal to the EPL.
However, different rules may apply (see table, e.g. `ss` must always point to a
writable segment with DPL equal to CPL).

LDTR and TR can only be changed explicitly in Ring 0 using the `lldt` and
`ltr` instructions.
The LDTR must be loaded with a selector pointing to a valid LDT descriptor in
the GDT.
The TR must be loaded with a selector pointing to a valid TSS descriptor in the
GDT.

.Conditions for successful update of segment registers
[cols="8"]
|===
.2+h| Mechanism
7+h| Target

| Data segment
| Nonconforming code segment
| Conforming code segment
| Call gate to nonconforming code segment
| Call gate to conforming code segment
| TSS or task gate
| Interrupt or trap gate

| Updating DS or ES
2+| `DPL >= EPL` and readable
| Readable
4+| Disallowed

| Updating SS
| `DPL == RPL == CPL` and writable
6+| Disallowed

| Updating CS through far `jmp`
.3+| Disallowed
.2+| `DPL == CPL && RPL \<= CPL`
.2+| `DPL \<= CPL`
| `gate DPL >= gate EPL && target DPL == CPL`
| `gate DPL >= gate EPL && target DPL \<= CPL`
.2+| `gate DPL >= tss EPL`
1+| Disallowed

| Updating CS through far `call` or `int`
2+| `gate DPL >= gate EPL && target DPL \<= CPL`
1+| `gate DPL >= CPL && target DPL \<= CPL` footnote:[Gate DPL is not checked if
    interrupt not caused by `int` instruction.]

| Updating CS through `retf` or `iret`
2+| `RPL >= CPL`
4+| Disallowed
|===

Segment registers may be changed implicitly through instructions (and
interrupts) that pass control flow to another code segment.
A control transfer to a nonconforming code segment, results in the CPL being
set to the DPL of the incoming code segment.
A control transfer to a conforming code segment results in no change in DPL.
Not just CS and IP may be changed as a result of a transfer to another code
segment.
If the operation results in a change in CPL, the stack is also switched
(meaning a change in SS and SP).

Control transfers may also target a TSS, instead of a code segment, resulting
in a task switch, with the task described by the TSS being resumed and the
state of the outgoing task being saved in the TSS of the outgoing task.
This results in most CPU registers (including LDTR) being changed and the
incoming task resuming at the state described by its TSS (including the CPL,
which is stored in the RPL field of CS and SS).

Operations that result in a change of code segment include far `jmp` and
`call`, which provide a far pointer, or an interrupt (that can be caused by an
`int` instruction), which provides an interrupt number.
Either way, these point to an unique segment descriptor.
The segment selector of the far pointer points to a segment descriptor in the
GDT or LDT, while the interrupt number points to a segment descriptor in the
IDT.

`jmp` and `call` may target a code segment, call gate or task gate.
A `jmp` instruction may not result in a change of CPL (violations of this, i.e.
through targeting a nonconforming segment with DPL not equal to CPL, result in
a general protection fault).

* If a code segment is targeted, control is transferred to that code segment at
  the offset provided as the operand of the instruction (assuming no protection
  violations or other faults).
  As with `jmp` instructions, a `call` instruction directly targeting a code
  segment may result in a change of CPL (i.e. it must be a "intra-level" call).
  `call` behaves similar to real mode, in the sense that it pushes a far
  pointer to stack for `retf` to pop.

* If a call gate is targeted, control is transferred to the code segment at the
  offset provided by the call gate descriptor, the offset provided by the
  instruction is ignored.
  A `call` to a call gate allows control to be transferred from less privileged
  code to more privileged code (i.e. the CPL gets lower, "inter-level call").
  If a change in CPL occurs, a stack switch to the stack corresponding to the
  new protection Ring, as defined in the TSS.
  If a stack switch occurs, the processor first pushes SS, SP, then copies the
  amount of words given in the word count descriptor field to the new stack and
  then pushes CS and IP.
  Note the call gate has following properties:

  . It is transparent to the application.
    The application simply does `jmp` or `call` as if it was a code segment.
  . The word count mechanism allows for transparent passing of parameters on
    the stack.
  . The offset operand of the `jmp` or `call` instruction is ignored.
    This prevents an application from entering the middle of a procedure or a
    procedure it should not enter.
  . The procedure can transparently return via `retf`.

* If a TSS or task gate is targeted, the task described by the TSS (or the TSS
  pointed to by the selector in the task gate) is resumed.
  For a procedure invoked via a TSS or task gate to properly return, it must
  use `iret`, not `retf`.

.16-bit intra-level far call stack
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp + 2` | Parameter 2 | Parameter 2 | `sp + 6`

| `sp` | Parameter 1 | Parameter 1 | `sp + 4`

| `sp - 2` .2+| | CS | `sp + 2`

| `sp - 4` | IP | `sp`
|===
====

.16-bit inter-level call gate stack
[%collapsible]
====
[cols="5*"]
|===
2+h| Caller stack
.8+h|
2+h| Callee stack

h| Address h| Content h| Content h| Address

| `sp + 6` .2+| Caller stack | SS | `sp + 10`

| `sp + 4`| SP | `sp + 8`

| `sp + 2` | Parameter 2 | Parameter 2 | `sp + 6`

| `sp` | Parameter 1 | Parameter 1 | `sp + 4`

2.2+| | CS | `sp + 2`

| IP | `sp`
|===
====

The actions of the `retf` instruction depends on the segment selector of the
far return pointer on the stack.
The selector part of the pointer must point to a valid code segment.
The RPL of that selector indicates the CPL of the caller.
If the RPL equals the CPL, no CPL change is necessary and the `retf`
instruction behaves like the `retf` instruction in real mode.
Otherwise, a stack switch occurs by restoring the caller SP and SS on the
callee stack.
In addition `retf` checks the DPL of DS and ES and sets them to null selectors
if they are lower than the caller CPL.

.16-bit TSS structure
[%collapsible]
====
[%header,cols="5,16*"]
|===
| Byte offset
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| 0 16+| Previous TSS selector backlink

| 2 16+| SP for Ring 0 (SP0)

| 4 16+| SS  for Ring 0 (SS0)

| 6 16+| SP for Ring 1 (SP1)

| 8 16+| SS  for Ring 1 (SS1)

| 10 16+| SP for Ring 2 (SP2)

| 12 16+| SS  for Ring 2 (SS2)

| 14 16+| IP

| 16 16+| FLAGS

| 18 16+| AX

| 20 16+| CX

| 22 16+| DX

| 24 16+| BX

| 26 16+| SP

| 28 16+| BP

| 30 16+| SI

| 32 16+| DI

| 34 16+| ES

| 36 16+| CS

| 38 16+| SS

| 40 16+| DS

| 42 16+| LDTR
|===
====

The RPL (and EPL) mechanism serves to prevent privilege escalation (i.e. a
less privileged program accessing privileged memory indirectly through a system
call, by passing a pointer to that portion of memory).
When a less privileged code passes a pointer to more privileged code, the
pointer can be tagged using the `arpl` instruction (which takes the maximum of
the CPL of the callee with the current RPL of the selector).
This means pointers are tagged with the CPL of the original caller.

For example, a procedure with CPL 3 passes a selector with RPL 0 pointing to a
descriptor with DPL 2 to a procedure with CPL 2 that in turn calls a procedure
with CPL 0.
When the procedure with CPL 2 is invoked, it executes `arpl` and sets the RPL
of the selector to 3 (which is the maximum of CPL 3 and RPL 0).
The procedure with CPL 0 also invokes `arpl` and the RPL of the selector
remains 3 (which is the maximum of CPL 2 and RPL 3).
Throughout all the stages, the EPL remains 3, which means a general protection
fault will be raised when accessing this pointer, even in Ring 0, since the EPL
is larger than the DPL.

==== Interrupts and task switching
The interrupts behave in a similar way to the `call` instruction.
Its effect depends on the corresponding IDT entry:

* If the target is an interrupt or trap gate, it behaves in a similar way to a
  call gate being invoked by a `call` instruction.
  The main difference is that no parameters from the caller stack are copied,
  if a privilege change occurs.
  Instead, the flags register is always pushed and the trap flag is cleared (in
  a similar fashion to interrupts in real mode).
  The only difference between an interrupt gate and a trap gate is that an
  interrupt gate clears the interrupt flag (much like real mode), while a trap
  gate does not.
* If the target is a task gate, it resumes the task described by the TSS the
  task gate points to, much like a `call` instruction.
  The interrupt flag of the incoming task is cleared.

In order to keep track of what interrupts and far calls were serviced by a task
gate, the CPU maintains the _nested task (NT) flag_.
Whenever a task switch due to an interrupt and call occurs, the NT flag of the
new task is set and the "previous TSS" field of the incoming task is filled
with the TSS selector of the outgoing task.
A task switch due to a jump clears the NT flag of the incoming task.

In addition, each TSS descriptor maintains a flag indicating whether the task
is "available" or "busy".
The currently executing task is always busy, along with the previous caller
chain.
Only an available task may be resumed through a task gate, while only a busy
task may be resumed through `iret`.
Entering a task gate results in the incoming task becoming busy.
While a `jmp` instruction causes the outgoing task to become available, `call`
instructions and interrupts result in the outgoing task remaining busy.
`iret` results in the callee becoming available once again.

The behavior of `iret` depends on the NT flag.
If the NT flag is cleared, `iret` behaves in a similar way to `retf`, except
that the FLAGS register (which was pushed on to the stack) is restored.
The IOPL is only changed, if the callee is at Ring 0.
If the NT flag is set, indicating an interrupt or call to a task gate, `iret`
causes a task switch to the task pointed to by the selector in the "previous
TSS" field (i.e. the caller task).
The NT flag of the callee (outgoing) task is subsequently cleared.

.16-bit intra-level interrupt or trap gate stack (without error code)
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp` | Caller stack | Caller stack | `sp + 6`

| `sp - 2` .4+| | FLAGS | `sp + 4`

| `sp - 4` | CS | `sp + 2`

| `sp - 6` | IP | `sp`
|===
====

.16-bit intra-level interrupt or trap gate stack (with error code)
[%collapsible]
====
|===
2+h| Before 2+h| After

h| Address 2+h| Content h| Address

| `sp` | Caller stack | Caller stack | `sp + 8`

| `sp - 2` .4+| | FLAGS | `sp + 6`

| `sp - 4` | CS | `sp + 4`

| `sp - 6` | IP | `sp + 2`

| `sp - 8` | Error code | `sp`
|===
====

.16-bit inter-level interrupt or trap gate stack (without error code)
[%collapsible]
====
[cols="5*"]
|===
2+h| Caller stack
.8+h|
2+h| Callee stack

h| Address h| Content h| Content h| Address

| `sp` | Caller stack | SS | `sp + 8`

2.4+| | SP | `sp + 6`

| FLAGS | `sp + 4`

| CS | `sp + 2`

| IP | `sp`
|===
====

.16-bit inter-level interrupt or trap gate stack (with error code)
[%collapsible]
====
.16-bit inter-level interrupt or trap gate stack (with error code)
[cols="5*"]
|===
2+h| Caller stack
.8+h|
2+h| Callee stack

h| Address h| Content h| Content h| Address

| `sp` | Caller stack | SS | `sp + 10`

2.5+| | SP | `sp + 8`

| FLAGS | `sp + 6`

| CS | `sp + 4`

| IP | `sp + 2`

| Error code | `sp`
|===
====

The 286 introduced a plethora of new exceptions.
Protected mode exceptions may push a 16-bit error code on top of the stack,
usually indicating a descriptor entry related to the exception (the exact
descriptor entry depends on the exact kind of exception).
The error may also be zero.

.Error code format
[cols="16*"]
|===
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

13+| Index 2+| TI | I | EX
|===

Index:: The index within the descriptor table.
Table indicator (TI):: Zero for GDT; one for LDT.
Interrupt (I):: Zero for GDT or LDT; one for IDT.
External (EX): Set, if exception caused by external interrupt.

Exceptions are classified in three types:footnote:[This terminology was
introduced with the 386.
The 286 manual differentiates between restartable (faults and traps) and
non-restartable exceptions (aborts).]

Fault:: Indicates a non-critical error has happened.
        These errors can be corrected and the program can be restarted at the
        faulting instruction.
Trap:: Traps allow a program to be restarted at the instruction following the
       trapping instruction.
Abort:: Aborts cannot be restarted reliably and indicate a critical error.

.286 exceptions
|===
| Vector | Name | Type | Class | Error code

| 0
| Divide by zero
| Fault
| Contributoryfootnote:[This is not a "protection violation", so would be
  considered benign, according to the 286 manual.]
| No

| 1
| Debug
| Trapfootnote:[Debug features in the 386 and later may dispatch a fault rather
  than a trap, as is the case for exceptions caused by the trap flag.]
| Benign
| No

| 3 | Breakpoint | Trap | Benign | No

| 4 | Overflow | Trap | Benign | No

| 5 | Bounds range exceeded | Fault | Benign | No

| 6 | Invalid opcode | Fault | Benign | No

| 7 | Coprocessor not present | Fault | Benign | No

| 8 | Double fault | Abort | Benign | Yesfootnote:[Always zero.]

| 9
| Coprocessor segment overrunfootnote:[486 and later never dispatch this
exception.]
| Abort
| Contributory
| No

| 10
| Invalid TSSfootnote:[May not be restartable on 386 and 486, if it happens
  when dispatching an interrupt.]
| Fault
| Contributory
| Yes

| 11 | Segment not present | Fault | Contributory | Yes

| 12 | Stack fault | Fault | Contributory | Yes

| 13
| General protection fault
| Faultfootnote:[With the 286, a segment limit overrun during a string
  operation, a general protection fault during a coprocessor segment overrun,
  and writing into a read-only segment through `adc`, `sbb`, `rcl` or `rcr` are
  not restartable.
  On later processors, a general protection fault is always restartable, but if
  it was caused while dispatching an interrupt, the interrupt may be lost.]
| Contributory
| Yes

| 16
| Coprocessor errorfootnote:[Motherboards may wire this interrupt somewhere
  else.
  XT-class PCs wired the FPU error pin to NMI.
  The IBM AT and most AT-class machines wire this to IRQ13, with the BIOS then
  redirecting it to NMI for compatibility.
  Some manufacturers wire it to NMI or to interrupt 16, causing compatibility
  problems.
  CPUs with integrated FPUs (i.e. 486 and later) have a flag on whether to
  route the instruction externally through the motherboard, or whether to use
  interrupt 16 internally.]
| Fault
| Benign
| No
|===

When an exception occurs while an exception handler is being dispatched, the
result depends on the kind of exception.
It may either handle them serially, dispatch a *dobule fault* or enter a
*triple fault*.
When a triple fault occurs, the processor shuts down.
Depending on the motherboard, this usually causes the computer to be rebooted.

Exceptions can be divided in into four relevant classes: benign, contributory,
page fault (introduced with the 386) and double fault.footnote:[The 286 manual
does not use this terminology, instead it differentiates between protection
violation and other, instead of contributory and benign.]

.Double exception handling
[cols="4*"]
|===
.2+h| First exception
3+h| Second exception

| Benign
| Contributory
| Page fault

| Benign
| Handled serially
| Handled serially
| Handled serially

| Contributory
| Handled serially
| Double fault
| Handled serially

| Page fault
| Handled serially
| Double fault
| Double fault

| Double fault
| Handled serially
| Triple fault
| Triple fault
|===

==== Machine Status Word
The 286 also introduced a new 16-bit register called the _Machine Status Word
(MSW)_, which can only be directly modified in Ring 0 through the `lmsw` and
`clts` instructions.

Protection enabled (PE):: Set for protected mode; clear for real mode.
                          May not be cleared once set on a 286 (later processors
                          allow returning back to real mode).
Monitor coprocessor (MP):: Raises coprocessor not present exception (interrupt
                           7) on `wait`, if MP _and_ TS are set.
                           Should be set, if a physical coprocessor is present
                           (i.e. the results become available asynchronously).
Emulate coprocessor (EM):: Raises coprocessor not present exception on `esc`
                           (i.e. on every floating-point instruction), if set.
                           Intended for emulating an FPU, if a physical one is
                           not present.
Task switched (TS):: Raises coprocessor not present exception on `esc`, if set.
                     Automatically set when task is switched, so that the
                     operating system is able to switch the x87 context for
                     tasks using floating-point instructions.
                     May be cleared again via `clts`.

MP, EM and TS also affect most MMX, 3DNow! and SSE instructions on later CPUs.

=== i386
The 386 introduced 32-bit extensions, paging, virtual 8086 mode and the ability
to return to real mode, in addition to new instructions and operand modes.
It also allows software to change the base and limit of the real mode IVT
through the IDTR.

==== 32-bit registers and addressing
The 386 expanded many registers to 32-bit registers.
These new dword-sized registers have the corresponding word-sized register
aliased to its lower word.
The new registers have an "e" prefix, to differentiate them from their 16-bit
counterpart.
For example, EAX is a 32-bit register, with AX aliasing to the lower word.
Similarly EBX, ECX, EDX, ESI, EDI, EBP, ESP, EIP and EFLAGS were added.

Segment registers and selectors remain word-sized, however offset sizes are
expanded to 32-bit, yielding a 48-bit logical address.
Two new data segment registers, similar to DS and ES, that can be used with
the corresponding segment override prefix, were introduced: FS and GS.

.386 registers
[%collapsible]
====
[%header,cols="3,32*"]
|===
| Register
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| EAX 16+| (EAX) 8+| AH (AX) 8+| AL (AX)

| ECX 16+| (ECX) 8+| CH (CX) 8+| CL (CX)

| EDX 16+| (EDX) 8+| DH (DX) 8+| DL (DX)

| EBX 16+| (EBX) 8+| BH (BX) 8+| BL (BX)

| ESP 16+| (ESP) 16+| SP

| EBP 16+| (EBP) 16+| BP

| ESI 16+| (ESI) 16+| SI

| EDI 16+| (EDI) 16+| DI

| EIP 16+| (EIP) 16+| IP

| EFLAGS
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | *VM* | *RF*
| 0 | NT 2+| IOPL | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| CR0
| *PG* | | | | | | | | | | | | | | |
| | | | | | | | | | | | *ET* | TS | EM | MP | PE

| CR2 32+| Page fault linear address

| CR3 20+| Page Directory Base Register (PDBR)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0

.3+| ES footnote:[The arrangement of fields in the hidden descriptor caches
     is arbitrary.]
12+| _Atrributes_ 4+| 16+| ES (visible selector)
32+| _Base_ 32+| _Limit_

.3+| CS 12+| _Attributes_ 4+| 14+| (visible CS selector) 2+| CPL
32+| _Base_ 32+| _Limit_

.3+| SS 12+| _Attributes_ 4+| 14+| (visible SS selector) 2+| CPL
32+| _Base_ 32+| _Limit_

.3+| DS 12+| _Attributes_ 4+| 16+| DS (visible selector)
32+| _Base_ 32+| _Limit_

.3+| FS 12+| _Attributes_ 4+| 16+| FS (visible selector)
32+| _Base_ 32+| _Limit_

.3+| GS 12+| _Attributes_ 4+| 16+| GS (visible selector)
32+| _Base_ 32+| _Limit_

.3+| TR 16+| 16+| TR (visible selector)
32+| _Base_ 12+| _Attributes_ 4+| 16+| _Limit_

.3+| LDTR 16+| 16+| LDTR (visible selector)
32+| _Base_ 16+| 16+| _Limit_

.2+| GDTR 32+| Base 16+| 16+| Limit

.2+| IDR 32+| Base 16+| 16+| Limit
|===
====

In addition to adding 32-bit variants to certain instructions (such as adding
`lodsd` to complement `lodsw` and `lodsb`), the 386 introduced new instructions
and instruction modes, in order to make the instruction set more orthogonal.
For example, `lss`, `lfs` and `lgs` instructions, in addition to the existing
`lds` and `les` instructions, new modes for `imul`, and near conditional jumps
(in addition to existing short conditional jumps) were added.
Completely new instructions were also added, such as instructions to sign
extend and zero extend smaller registers into larger registers `movsx` and
`movzx`.

The 386 decides whether to use 32-bit or 16-bit registers based on the current
code segment.
A 32-bit code segment interprets instructions as operations on 32-bit and
8-bit registers and memory locations and used 32-bit offsets.
A 16-bit code segment interprets instructions as operations on 16-bit and
8-bit registers and memory locations and used 16-bit offsets, in the same way
as previous 16-bit processors of the x86 line.
16-bit operands and addresses can be used in a 32-bit code segment and vice
versa using the *operand size prefix* and *address size prefix*.

32-bit effective addresses are significantly more orthogonal as their 16-bit
counterparts.
As with 16-bit addresses, 32-bit addresses may have a base, an index and a
displacement.
In addition, a *scale* may be added, that is multiplied with the index.

* base - any 32-bit general-purpose register (EAX, EBX, ECX, EDX, ESI, EDI,
  EBP, ESP)
* index - any 32-bit general-purpose register, except ESP (EAX, EBX, ECX, EDX,
  ESI, EDI, EBP)
* scale - 1, 2, 4 or 8
* displacement - zero, 8-bit sign extended value or 32-bit value

Following combinations are allowed:

* `displacement` alone
* `base` alone
* `base + displacement`
* `index * scale + displacement`
* `base + index + displacement`
* `base + index * scale + displacement`

The default segment is DS, except if the base is EBP or ESP, in which
case the default segment is SS.

==== 32-bit segmentation
In order to deal with 32-bit addresses and the extended 32-bit physical address
space, the 386 introduces backwards-compatible changes to segmentation.

.386 segment descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 8+| Base (31:24) | G | DB | 0 | A 4+| Limit (19:16)

| +32 | P 2+| DPL | S 4+| Type 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit (15:0)
|===

Limit:: The Limit field has been extended from 16-bit to 20-bit, allowing a
        limit of up to 1 MiB (or 4 GiB using the G-flag).
Base:: Extended to 32-bit.
Available (A):: Available for use by the operating system.
DB:: Set for 32-bit segment; clear for 16-bit segment.
     Called the D flag for code segments and the B flag for data segments.
     Meaning depends on type of segment:
     * For a code segment, it defines the default operand and address
       size.
     * For a stack segment, it defines the size of the stack pointer (i.e.
       whether to use just SP or all of ESP for stack operations).
     * For a expand-down segment, it defines the upper bound.
       16-bit expand-down segments have an upper bound of 0xFFFF.
       32-bit expand-down segments have an upper bound of 0xFFFFFFFF.
Granularity flag (G):: If set, limit is given in 4 kiB units, rather than units
                       of one byte.
                       The effective limit is `limit * 4096 + 4095`.
                        Allows for segments of up to 4 GiB.

.New 386 system segment types
[cols="4*,5,6"]
|===
| 43 | 42 | 41 | 40 | Segment type | Descriptor tables

| 1 | 0 | 0 | 1 | Available 32-bit TSS | GDT only

| 1 | 0 | 1 | 1 | Busy 32-bit TSS | GDT only

| 1 | 1 | 0 | 0 | 32-bit call gate | All

| 1 | 1 | 1 | 0 | 32-bit interrupt gate | IDT only

| 1 | 1 | 1 | 1 | 32-bit trap gate | IDT only
|===

Aside from the new 32-bit segments and gates, 386 segmentation fundamentally
works the same as on the 286.
Even the behavior of the stack for 32-bit calls and interrupts work essentially
the same, except that 32-bit registers are pushed, instead of 16-bit registers,
and 16-bit selectors and error codes are padded with an extra high word, in
order to become 32-bit.
The bit size of calls and interrupts is determined by the operand size for
calls directly targeting code segments and by the type of gate for calls and
interrupts through gates.

.32-bit gate descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Offset (31:16)

| +32 | P 2+| DPL | S 4+| Type 3+| Reserved 5+| Word count

| +16 16+| Segment

| +0 16+| Offset (15:0)
|===

Thus, 16-bit and 32-bit segments and gates can be largely mixed.
However, the size of the return instructions must match the size of the call
instructions and a 16-bit call from a 32-bit segment will truncate EIP.
For a 16-bit call to work as expected, it must be called from the first 64 kiB
of a segment, and can only target the first 64 kiB.

The `lgdt` and `lidt` instructions work identically to the 286, except that the
reserved byte is now used to extend the base address field to 32 bits.

.386 pseudo-descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +32 16+| Base (31:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

It is not recommended to mix 16-bit and 32-bit task state segments, due to
unintended side-effects of missing fields.
In particular, a 32-bit TSS stores the state of CR3 (i.e. the Page Directory
Base Register PDBR) and the new general-purpose registers introduced with the
386.

.32-bit TSS structure
[%collapsible]
====
[cols="1,1,1"]
|===
| Byte offset | +2 | +0

| 0 | Reserved | Previous TSS

| 4 2+| `esp0`

| 8 | Reserved | `ss0`

| 12 2+| `esp1`

| 16 | Reserved | `ss1`

| 20 2+| `esp2`

| 24 | Reserved | `ss2`

| 28 2+| `cr3` (`pdbr`)

| 32 2+| `eip`

| 36 2+| `eflags`

| 40 2+| `eax`

| 44 2+| `ecx`

| 48 2+| `edx`

| 52 2+| `ebx`

| 56 2+| `esp`

| 60 2+| `ebp`

| 64 2+| `esi`

| 68 2+| `edi`

| 72 | Reserved | `es`

| 76 | Reserved | `cs`

| 80 | Reserved | `ss`

| 84 | Reserved | `ds`

| 88 | Reserved | `fs`

| 92 | Reserved | `gs`

| 96 | Reserved | `ldtr`

| 100 | I/O map base | T flag
|===
====

I/O map base:: Base offset of a bitmap in the TSS.
               This allows code running at a CPL higher than the IOPL to have
               limited access to I/O.
               In particular, each bit corresponds to an I/O port.
               If the bit is cleared, code at any CPL may access that I/O port.
               The TSS does not need to contain a complete I/O port bitmap,
               bits beyond the limit of the TSS are treated as being set,
               thereby preventing unprivileged access to the corresponding
               ports.footnote:[Word or dword I/O to unaligned ports may cross a
               byte boundary, meaning two bytes need to be loaded.
               Thus it is recommended to have an extra byte after the highest
               I/O port that is accessed, with numerical value 255.]
T flag (T):: Bit 0 of the corresponding word in the table.
             All other bits are reserved.
             If set, will raise a debug trap (interrupt 1), when switching to the
             task.

==== Paging
The 386 added support for paging as an extra translation layer, in addition to
segmentation.
With paging enabled, segments are not contiguous ranges in physical address
space, but rather _virtual address space_.
In particular, the base of segments is treated as a _linear address_, rather
than a physical address.
Segmentation translates a logical address, consisting of a 16-bit segment
address and a 32-bit offset, to a 32-bit linear address.
Paging is responsible for converting this linear address to a physical address.

This is achieved, by divided both virtual and physical 4 GiB address spaces
into 1048576 aligned pages of 4096 bytes.
Paging maps pages of physical memory to certain spots in virtual memory.
This effectively creates a flat address space that is isolated from physical
memory, allowing for greater isolation of software.

Protected mode segmentation allows for a similar degree of isolation.
Segments however need to be contiguous and have variable size.
Pages have fixed size and are invisible to application programs, allowing for
memory to be arbitrarily fragmented and swapped out in chunks of 4096 bytes.

Entries in the translation table are 32-bit, so instead of having a single page
table of 2 MiB (more RAM than many systems had at the time), the 386 employs a
two-level paging system.
The root page table is the *page directory (PD)*, which has entries pointing to
individual *page tables (PT)*, which consists of entries pointing to the
physical base address of individual pages.

Both of these tables occupy 4 kiB and thus have 1024 entries.
This means each page table (corresponding to one entry in the page directory)
contains the mapping for 2 MiB of virtual memory.
Each entry in the page table determines the mapping of a 4 kiB page.

Thus, the linear address is split into three parts.
The most significant bits determines what PT within the PD to look up (PD
index).
The middle part determines what page entry to look up within the PT (PT entry).
The least significant part is the offset within the page itself.

.32-bit linear address
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

10+| PD index (0-1023) 10+| PT index (0-1023) 12+| Offset (0-4095)
|===

The physical address of the PD is given by CR3.
Both CR3 and entries in the PD and PT are 32-bit physical addresses pointing to
a PD, PT or page respectively.
Since all these structures must be aligned with page boundaries, the lower
12 bits of the physical address are always zero and are used for other
purposes.
All of these 12 bits are reserved in CR3 and should be zero.
The upper 20 bits of CR3 are known as the PDBR, or _Page Directory Base
Register_.

.386 page entry
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

20+| Physical address (31:12)
3+| Available | 0 | 0 | D | A | 0 |0 | U/S | R/W | P
|===

Physical address:: The physical address of the page (for a PT entry), PT (for a
                   PD entry).
                   Since pages, PTs and PDs must be aligned, the lower 12 bits
                   have a different meaning, and are effectively zero when
                   determining the 32-bit physical base address.
                   Alternatively, one can thinking of the 20-bit field as the
                   index of the page in physical memory.
Available:: These bits are available for use by the operating system.
Dirty bit (D):: PT entries only.
                The CPU automatically sets this bit when the corresponding page
                is written to.
Accessed bit (A):: The CPU automatically sets this bit when the corresponding
                   page, or a page mapped in the corresponding PT, is read or
                   written to.
User/supervisor flag (U/S):: Zero for supervisor; one for user.
                             User pages may be accessed by code at CPL 3.
                             Supervisor pages may only be accessed by Rings 0,
                             1 and 2.
Read/write flag (R/W):: Zero for read-only; one for read-write; .
                        Read-only pages may not be written to by code at CPL 3.
Present bit (P):: One indicates the entry may be used.
                  If zero, accessing the corresponding page or PT will cause a
                  page fault and all the other bits may be used by the
                  operating system.

Page protection violations result in a page fault.
Both PT and PD entries hold permission bits.
For a page to be a user page, the U/S flag must be set in the corresponding PT
_and_ PD entry.
For a page to be a read-only page, the R/W flag must also be set both in the PT
_and_ in the PD.
This effectively means, the PD entry serves as an override to the corresponding
PT entries, that restricts permissions further.

The present bit works in a similar way in relation to whether the page may be
accessed.
If the PT itself is not present (indicated by a zero in the present bit of the
corresponding entry in the PD), the PD may not be accessed.

[NOTE]
CPUs have a _translation look-aside buffer (TLB)_, that is effectively a cache
of page entries, so the CPU does not have to constantly fetch pages entries
from the PD and PT.
This is mostly transparent to the operating system, however the TLB should be
flushed when a page entry is changed that results in some form of more
restricted access compared to the previous state (relaxing access control
does not need a TLB flush, since the processor will load the entry again before
throwing a page fault).
The TLB can be flushed by writing to CR3.

Due to 32-bit addressing, a single segment can now span all of the 4 GiB
virtual address space.
This means programs no longer need to be split into multiple segments, instead
having a single flat segment starting at linear address zero, similar to the
tiny memory model.
Most modern operating systems on the x86 architecture employ this *flat memory
model* and use paging, rather than segmentation, as the primary mechanism for
virtual memory.
This means the GDT only contains a handful of actual segments and the LDT is
completely ignored.

In this scheme, each process has its own, isolated virtual address space.
This is facilitated by the fact that the TSS has an entry for CR3.
Another advantage of the two-level paging scheme is that common areas of
virtual memories can be mapped in only one set of page tables, that can be then
mapped in the page directory of each individual process, instead of each
process having a its own set of identical page tables for the common area of
virtual memory.

One disadvantage of paging is that it has less fine control over access
permissions.
Pages are aligned 4 kiB blocks, and effectively only have two privilege levels.
Many operating system, however, only use Ring 0 and Ring 3 anyways.
Another problem is that there is no way to restrict execution of pages, while
still allowing it to be read or written.

Modern operating systems implement context switching in software, rather than
using the hardware context switching facilities.
Modern processors no longer optimize hardware context switching.
In particular, this means there is a fixed amount of task state segments,
meaning, in combination with the flat memory model, that modern operating
systems typically have a fixed amount of entries in the GDT.

==== Page fault ====
The 386 introduces a new exception:

.New 386 exceptions
|===
| Vector | Name | Type | Class | Error code
| 14 | Page fault | Fault | Page fault | Yes
|===

This new exception is special in certain regards:

* Double exception handling is different.
  If a page fault occurs during a contributory exception, the fault and
  exception are handled serially.
  However, if a contributory exception occurs during a page fault, a double
  fault is raised.

* The error code does not provide an entry in a segment descriptor table.
  Instead it consists of flags indicating the nature of the memory access that
  caused the page fault.
  CR2 stores the target linear address that caused the page fault.

.Page fault error code
[cols="16*"]
|===
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

12+| Reserved | RSVD | U/S | W/R | P
|===

Present (P):: Zero for a fault caused by a non-present page; one for a
              protection violation.
Write/read flag (W/R):: Zero for a fault caused by a read; one for a fault
                        caused by a write.
User/supervisor flag (U/S):: Zero for a fault caused by a process in user mode;
                             one for a fault caused by a process in supervisor
                             mode.
Reserved flag (RSVD):: One if the fault was caused by a reserved bit set to
                       one.
                       P6 and later.

==== Control registers ====
The 386 introduced eight 32-bit control registers CR0 to CR7, that can be
accessed through a regular `mov` instruction to or from a general-purpose
register.

CR0 is a 32-bit extension to the 16-bit MSW that adds to new flags:

Extension type (ET):: Zero for a 287; one for a 387.
                      The 386 automatically initializes this bit.
Paging (PG):: Zero disables paging; one enables paging.
              Must not be set, if PE is zero.

CR1 and CR4 to CR7 are reserved for future use and cause an undefined opcode
exception.

CR2 stores the linear address of the memory location that triggered a page
fault.

CR3 contains the Page Directory Base Table (PDBR), the physical address of
the page directory.
Since the page directory must be page-aligned, the lower 12 bits are reserved.

==== Debugging ====
Previous x86 CPUs already have certain debugging facilities:

* Interrupt 1, that is invoked on every instruction when the trap flag (TF) is
  set.
  This feature allows for single-stepping.
* Interrupt 3, that can be invoked by the one-byte instruction `int3`, allowing
  for breakpoints.

In addition, the 386 introduces the ability to trap a task through a flag in
the TSS and to invoke interrupt 1 via the one-byte `int1` instruction.

[NOTE]
Intel reserves `int1` for debugging hardware, while software debuggers should
use `int3`.

The 386 also introduces eight debug registers DR0 to DR7.
Much like CR1, DR4 and DR5 are reserved and cause an undefined opcode
exception when accessed.

DR0 to DR3 contain the linear address of breakpoints zero through three.
DR6 is known as the _Debug Status Register_ and DR7 is known as the _Debug
Control Register_.

== Floating-point and vector extensions
x86 processors have a plethora of extensions that expand on the general-purpose
instruction set.

=== x87
*x87*, also known as _Numerical Processing Extension (NPX)_ or _FPU_, is a
scalar floating-point calculation extension.
Units that implement x87 are often referred to as "the FPU", although the term
may also apply to the SIMD floating-point extensions listed below.
Originally implemented as a separate coprocessor, it is integrated into the
486DX and most processors that came after it.

The instruction set primarily operates on a stack of eight 80-bit registers
that are addressed as ST(0) to ST(7) relative to the top of the stack.

=== MMX
*Multimedia Extensions (MMX)* is a SIMD (single instruction; multiple data)
extension introduced in 1997 with the Pentium MMX.
AMD first implemented MMX in the K6 in 1997.
MMX only supported integer math and operated on aliases to the 64-bit
significand part of the x87 registers, called MM0 to MM7.
Unlike x87, MMX can addresses those registers directly, without a stack
pointer.
This aliasing makes it difficult for applications to use MMX and x87 at the
same time.

==== 3DNow!
In 1998, AMD introduced *3DNow!* with the K6-2.
This extended MMX to introduce support for operations on 32-bit floating-point
data.
AMD introduced an extended version of 3DNow! in 1999 with the original Athlon.
This also included a subset of new MMX integer instructions introduced with
SEE.
Starting with AMD Bulldozer CPUs, 3DNow! is no longer supported (except for two
instructions that are also found in newer Intel processors).

=== SSE
*Streaming SIMD Extensions (SSE)*, also known as _Katmai New Instructions (KNI)_
or _Internet Streaming SIMD Extensions (ISSE)_, is a SIMD extension introduced
in 1999 with the Intel Pentium III and supported by AMD since the Athlon XP in
2001.
In addition to adding new instructions to the existing MMX integer instruction
set, it introduces a new set of eight 128-bit registers XMM0 to XMM7 that
can each store four 32-bit floating-point numbers.

==== SSE2
*SSE2*, also known as _Willamette New Instructions (WNI)_, was introduced in 2000
with the Intel Penium 4.
AMD first implemented it with the x86-64 Opteron in 2003.
SSE2 adds support for 64-bit floating-point numbers and integers of sizes
ranging from 8-bit to 64-bit, through MMX-like instructions on SSE registers.
Thus, it is a full replacement of MMX and a partial replacement for x87 (though
x87 supports higher precision 80-bit floating-point math).

AMD's x86-64 implementation introduced eight new registers XMM8 to XMM15,
that can only be used in 64-bit mode.
Infact, SSE2 with 16 registers is mandatory for every x86-64 implementation.

==== SSE3
*SSE3*, also known as _Prescott New Instructions (PNI)_, was introduced by Intel
in 2004 with the Prescott Pentium 4 and by AMD in 2005 with the Athlon XP
Revision E.
This extension introduced support for "horizontal" operations between values in
the same register.

==== SSSE3
*Supplementary Streaming SMD Extenions 3 (SSSE3)*, also known as _Merom New
Instructions (MNI)_, was first implemented by Intel in 2006 with Woodcrest Xeons
and by AMD with Bulldozer AMD FX CPUs in 2011.
It is not to be confused with SSE4.

==== SSE4
*SSE4*, was divided into two subsets by Intel.
The first subset, *SSE4.1*, also known as _Penryn New Instructions (PNI)_, was
introduced with Penryn Core 2 CPUs in 2007.
The second subset, *SSE4.2*, also known as _String and Text New Instructions
(STTNI)_, was introduced with Nehalem Core i7 CPUs in 2008.
Nehalem also introduced performance improvements for misaligned data.
While SSE4.1 added new SIMD instructions, such as a dot product instruction,
SSE4.2 added string search and comparison instructions and a CRC32 instruction.

AMD introduced its own subset of SSE4, *SSE4A*, with the K10 in 2007.
SSE4A introduces four instructions not available on any Intel processor.
AMD started supporting the full SSE4 instruction set with the Bulldozer
architecture in 2011.
With SSE4A, AMD also introduced greater support for operations with misaligned
data, which is supported by Intel since AVX.

==== SSE5
*SSE5* was a proposed extension by AMD in 2007.
It does not include all SSE4 instructions and proposed a new _DREX encoding_,
which is incompatible with AVX's VEX encoding.
This extension was never implemented in hardware and had to be revised and
split into  F16C, XOP and FMA4 in 2009, in order to remain compatible with AVX.

==== F16C
*F16C*, also known as *CVT16* originally proposed by AMD in 2009, it adds
instructions to convert between half-precision and single-precision
floating-point numbers.
It was first implemented by AMD with Bulldozer in 2011 and by Intel with Ivy
Bridge in 2012.

==== XOP
*Extended Operations (XOP)* adds new vector instructions to SSE and was first
proposed by AMD in 2015 and first implemented in Bulldozer in 2011.
XOP does not use the VEX coding scheme of AVX.
No Intel CPU implemented XOP and AMD dropped support with Zen in 2017.

==== FMA
There exist two variants of *Fused Multiply-Add (FMA)*: the three-operand
*FMA3* and the four-operand *FMA4*.
The original instructions in SSE5 were three-operand DREX-encoded.
Intel's original AVX specification specified a VEX-encoded four-operand
version (FMA4).
Later, Intel changed it to a three-operand VEX-encoded version (FMA3).

AMD first implemented FMA4 with Bulldozer in 2011 and FMA3 with Piledriver in
2012.
Intel never implemented FMA4 and implemented FMA3 with Haswell in 2013.
AMD dropped official support for FMA4 with Zen in 2017.

=== AVX
*Advanced Vector Extensions (AVX)* was first proposed by Intel in 2008 and
implemented in 2011 by Intel with Sandy Bridge and by AMD with Bulldozer.
It introduces the new _VEX instruction coding_ scheme and expands the 128-bit
XMM SSE registers to 256-bit YMM registers (YMM0 to YMM15).
The VEX coding scheme allows three-operand operations, relaxes alignment
requirements and allows 128-bit operations.

==== AVX2
*AVX2* is an extension to AVX introduced by Intel in 2013 with Haswell and by
AMD in 2015 with Excavator.

==== AVX-512
*AVX-512* is a set of extensions first proposed by Intel in 2013 and first
implemented in 2015.
AVX-512 consists of multiple instruction sets, with only _AVX-512F_ (Foundation)
being mandatory.
AVX-512 expands the 256-bit AVX registers to 512-bit registers and introduces
the new _EVEX coding scheme_, allowing for 32 registers (ZMM0 to ZMM31).
The _AVX-512VL_ (vector length) set allows the use of AVX-512 operations on
256-bit (YMM0 to YMM31) and 128-bit (XMM0 to XMM31) operands.

==== AVX-VNNI
*AVX-VNNI* allows for _AVX-512VNNI_ (virtual neural network interface)
instructions on 128-bit and 256-bit operands using the VEX encoding for CPUs
that do not yet fully support AVX-512.

== Bit manipulation extensions
Newer x86 implementations support non-SIMD *bit manipulation instructions sets
(BMI)*, that operate on general-purpose registers.

=== ABM
*Advanced Bit Manipulation (ABM)* consists of the instructions `popcnt` and
`lzcnt`, and was introduced by AMD with SSE4A.
Intel introduced `popcnt` as part of SSE4.2 and `lzcnt` as part of BMI1.

=== BMI1
*Bit Manipulation Instruction Set 1 (BMI1)* was introduced by AMD with
Piledriver in 2012 and implemented by Intel with Haswell in 2013.

=== TBM
*Trailing Bit Manipulation (TBM)* was introduced by AMD with Piledriver in 2012
and was never implemented by Intel.
Zen-based processors do not support TBM.

=== BMI2
*Bit Manipulation Instruction Set 2 (BMI2)* was introduced by Intel with
Haswell in 2013 and supported by AMD since Excavator in 2015.

=== ADX
*Multi-Precision Add-Carry Instruction Extensions (ADX)* is an extension
introduced by Intel with Broadwell in 2014 and supported by AMD since Zen in
2017.
It introduces instructions for the efficient adding of large integers.

== External links
* https://en.wikipedia.org/wiki/X86[x86 on Wikipedia]
