---
title: x86
tags: x86, architecture
category: x86
description: Introduction to the x86 CPU architecture.
---

*x86* is a backwards compatible family of little-endian complex instruction
set architectures introduced in 1978 by Intel.
The two preeminent manufacturers of CPUs implementing x86 are Intel and AMD.
The iterations of the ISA can be broadly classified by integer width:

* 16-bit x86, also referred to as *IA-16*, *x86-16*, or *x86_16* (introduced
  with the Intel 8086 in 1978).
* 32-bit x86, also referred to as *IA-32*, *x86-32*, or *x86_32* (introduced
  with the Intel 386 in 1985).
* 64-bit x86 (not to be confused with IA-64), also referred to as *x86-64*,
  *x86_64*, *AMD64*, or *x64*.
  It is also referred to as _EM64T_, _IA-32e_, or _Intel64_ by Intel.

== History
=== First generation
The first iteration of the x86 architecture was introduced in 1978 with the
*Intel 8086*.
The 8086 is a 16-bit CPU with 16-bit registers, a 16-bit data bus, and a 20-bit
address bus.
Thus, it is able to address one mebibyte of RAM.
Although the 8086 has no binary compatibility with the 8080 or 8085, it is
designed to allow all 8080 or 8085 programs to be machine translated to work on
the 8086.

Slightly later, the *Intel 8088* was introduced.
The 8088 is internally identical to the 8086, but had a 8-bit data bus, and was
used by the original IBM PC, introduced in 1981, the predecessor of all modern
PCs.
Thus, the x86 architecture became the dominant architecture on personal
computers.

Intel also introduced the *Intel 8087* FPU, which provides floating-point
capabilities, and operates in parallel to the main processor.
The _Intel 8089_ IOP (I/O processor) was also introduced to allow fast I/O
operations without CPU supervision, allowing for an increasing degree of
parallelism.
However, the IBM PC does not use the 8089, instead, using the simpler Intel
8237 (designed for the 8-bit 8085).
Consequently, no successor to the 8089 was ever made.

=== Second generation
In 1982, Intel introduced the *Intel 80186*, *Intel 80188*, and *Intel 80286*
(also known as the 186, 188, and 286 respectively).
The 186 and 188 are similar to the 8086 and 8088 respectively, but are intended
for embedded systems, and integrate peripherals, that are not compatible with
IBM PCs.

Although the 8087 is compatible with both the 186 and 187, the *Intel 80187*
(also known as the 187) was introduced much later as a math coprocessor
compatible the 186 (but not the 188).
The 187 is internally more similar to the 387, supports all the 387
instructions, and is IEEE 754 compliant.

The 286, however, is intended for multi-user multitasking environments.
Thus, the 286 introduces features for multitasking and memory protection, and
is able to address up to 16 MiBs of RAM.
To preserve compatibility with the 8086, most of the features introduced with
the 286 can only be used in a mode called _protected mode_.
The 286 and most subsequent x86 processors start in _real mode_, which emulates
the behavior of a 8086.
The 286 started to gain wide adoption with the introduction of the IBM AT in
1984.

The math coprocessor for the 286 is the *Intel 80287* (also known as the 287).
A later version of the 287, known as the 287XL, is internally similar to the
387SX.
The 287 is also compatible with the 386DX and 386SX.

=== NEC V20
The *NEC V20* is a pin compatible replacement for the 8088, and a very popular
upgrade for XT-class machines, due to being able to execute more instructions
on average in a smaller amount of time.
Variants include the *NEC V30*, which is pin compatible with the 8086, the
_NEC V40_, which corresponds to the 188, and the _NEC V50_, which corresponds
to the 186.
The _NEC V33_ and the _NEC V53_ are V30 and V50 variants with performance
equivalent to a 286, that are able to address up to 16 MiB of memory.
The _NEC V25_ and _NEC V35_ are microcontroller variants of the V20 and V30
respectively.
The later V60 series implements a different ISA, but has a V20 emulation mode.

All these CPUs support the 186 instruction set and new instructions exclusively
available on NEC CPUs.
Among other things, these instructions include nibble and bitwise operations.
The V25 and V35 implement additional enhancements, such as eight register banks
for interrupt handling.

In addition to the enhancements common to all V-series CPUs, the V20, V30, V40,
and V50 feature an _8080 emulation mode_, whereby 8080 binaries can be executed
without translation.

The V33 and V53 implement _expanded addressing mode_, which allows the use of
up to 16 MiB of RAM.
This mode is essentially real mode with paging of 16 kiB pages.
The 20-bit linear addresses are translated to 24-bit physical addresses with a
table at I/O ports 0xFF00-0xFF7F.

=== Third generation
In 1985, Intel introduced the *Intel 386DX*.
This new iteration introduced support for 32-bit integers and extended
protected mode to introduce, among other things, paging, and support for up to
4 GiBs of RAM.
Later, Intel introduced the *Intel 386SX*, which is internally similar to the
386DX, but has a 16-bit data bus and 24-bit address bus rather than 32-bit
busses.

In 1987, the *Intel 387DX* was introduced.
Due to its 32-bit data bus, it is incompatible with the 386SX, which has its
own math coprocessor called the *387SX*.

=== Fourth generation
*Intel 486DX* was introduced in 1989 and implements new features, such as
tightly coupled (i.e. true) pipelining and an integrated FPU.
The *Intel 486SX* variant is a version without an integrated FPU.footnote:[Early
486SX chips are actually 486DX chips with the FPU disabled.]
An *Intel 487SX* math coprocessor upgrade was available for 486SX
systems.footnote:[The 487SX is actually a full 486DX, that disables the 486SX
completely.]

=== Fifth generation
In 1993, the *Intel Pentium* was introduced, featuring the new *P5* (also known
as *i586*) microarchitecture, which introduces superscalar architecture, a
64-bit external data bus and branch prediction.
The Pentium MMX, introduced in 1997, first implemented the new MMX SIMD
extension.

Intel's competitors also started building their chips on their own unique
in-house 586-class designs, such as the AMD K5 (1996), the Cyrix 5x86 (1995)
and 6x86 (1996), the NexGen Nx586 (1994, did initially not have an integrated
FPU, but a discrete Nx587 existed), and the Centaur WinChip (1997), rather than
trying to replicate Intel's chips, as with the Am486, Am5x86 and Cx486.

=== Cyrix extensions
Cyrix processors and their derivatives made by National Semiconductors, AMD,
and VIA implement extensions, that are not found on any other processor.
Opcodes for those instructions were often reused by other manufacturers.

All Cyrix processors, starting with late Cx486 CPUs, include extensions to
system management mode.
The 6x86MX and MII implement an extension to MMX, called
_Extended Multimedia Instructions (EMMI)_, and an additional extension to SMM.
MediaGX and Geode GXm, GXLV, and GX1 processors implement special instructions
for display drivers for the on-chip video.
Geode GX2 and AMD Geode introduce a _debug management mode (DMM)_.

=== Sixth generation
The Pentium was followed up by the Pentium Pro in 1995, which is the first
implementation of the *P6* (also known as *i686*) microarchitecture,
introducing register renaming, out-of-order execution, speculative execution,
and a 36-bit address bus, allowing for up to 64 GiBs of RAM, that could be
accessed through PAE or PSE-36.

The Pentium II, introduced in 1998, is a P6 processor with MMX.
The Pentium II was followed up by the Pentium III in 1999.
AMD released the 686-class K6 (based on the Nx586) in 1997, followed up by the
K6-2 in 1998, and K6-III in 1999.

=== Seventh generation
Seventh generation processors include the NetBurst-based Pentium 4, introduced
in 2000, and the AMD Athlon, also known as the K7, introduced in 1999.
A major feature of the Pentium 4 is SSE2.

In addition, VIA introduced its own x86 chips in 2000 (mostly based on
Centaur's WinChip), after buying Cyrix and Centaur.
Notably, the VIA PadLock instruction set extension was introduced in 2003,
which provides fast random number generation, encryption, and hashing, and is
not available on Intel and AMD processors.

=== x86-64
The first processors to implement *x86-64*, a 64-bit extension, originally
proposed by AMD in 1999, are the AMD Opteron and Athlon 64, also known as the
K8, introduced in 2003.
Aside from increasing the size and count of general-purpose and SSE registers,
it introduces 64-bit linear addresses, albeit the paging scheme restricts the
linear address space to 48 bits (splitting it into to halves through sign
extension).

To maintain backwards compatibility, these new features can only be used in
long mode.
In long mode, many legacy features, such as segmentation and hardware task
switching, are restricted or unavailable.
The behavior compatible with older CPUs (i.e. real and protected mode) is
available in legacy mode.

To this day, every properly-implemented x86 processor has a large degree of
binary backwards compatibility, all the way back to the original Intel 8086.

== Operating modes
x86 has a handful of operating modes.
On x86-64 processors, real mode and protected mode are grouped together into
*legacy mode*.

=== Real mode
*Real mode* is the operating mode that an x86 processor boots into.
It mostly models the original 16-bit 8086 processor, with a few extensions.
Real mode contains no access rings or memory protection of any kind.

Access to memory is done via a 16-bit _segment address_ and a 16-bit _offset_,
using following formula:

[source]
physical_address = segment * 16 + offset

The default operand and address size is 16-bit.
The segment limit is 65536 bytes (64 kiB).
This means even when using a 32-bit address size prefix, the offset may not
exceed 65535.

Due to these limitations, software in real mode can only directly access the
first 1114096 (1 MiB + 64 kiB - 16 bytes) of physical memory:

[source]
65535 * 16 + 65536 = 1114096

==== Unreal mode
_Unreal mode_, also known as _flat real mode_, _32-bit real mode_. or _voodoo
mode_, is an originally undocumented variant of real mode that alters the
segment descriptor cache, in order to allow 32-bit offsets, so that programs
may access up to 4 GiB of memory.
Unreal mode is available on the 386 and above.

===== Big real mode
_Big real mode_, also known as _big unreal mode_, sets the limit of data
segments to 4 GiB, allowing for a flat 32-bit physical address space
starting from zero if segment zero is used.

===== Huge real mode
_Huge real mode_, also known as _huge unreal mode_, sets the limit of code
segments to 4 GiB, in addition to changing the data segment limit.
However, the high 16 bits of EIP are not saved by real mode interrupts,
making it difficult to use.

=== Protected mode
*Protected mode* was introduced with the 286 and provides memory protection.
Unlike real mode, there is no linear relationship between segment address and
segment base address.
The segment base address and other properties of each segment are determined by
the _global descriptor table (GDT)_ and _local descriptor table (LDT)_.
The segment address is now a segment selector, which is essentially an index
to a segment descriptor.

Protected mode provides four protection rings, Ring 0 being the most privileged
and Ring 3 being the least privileged.
Most operating systems only use Ring 0 and Ring 3.
Code running in Ring 0 may access any segment and may interface directly with
hardware.
The privileges of other Rings depend on the GDT and LDT and the state of the
CPU.
Ring 0 is often referred to as "kernel mode", and Ring 3 is often referred to
as "user mode".

The 286 allows for up to 16 MiB of RAM.
However, extensions to protected mode introduced with the 386 increase this to
4 GiB.
The 386 also introduces optional paging to protected mode, allowing for an
extra level of translation after segmentation.
Later extensions, such as PAE and PSE-36, increase the maximum size of physical
memory to beyond 4 GiB.
However, the size of linear address space is still limited to 4 GiB.

Thus, the _logical address_, consisting of segment selector and offset, is
first translated to a _linear address_, by adding the segment base address of
the corresponding segment descriptor to the offset.
If paging is enabled, the linear address is translated to a _physical address_,
otherwise the linear address corresponds to the physical address.

Protected mode has two sub-modes, depending on the current code segment.
However, 16-bit and 32-bit segment descriptors may coexist in the same
descriptor table.

==== 16-bit protected mode
If the current code segment is a 16-bit segment, the default address and
operand size is 16-bit.

Code targeting real mode is largely compatible with 16-bit protected mode,
assuming, among other things, it does not attempt to do any privileged
operation, does not assume that there is a direct relationship between segment
base and segment address (as is the case in real mode), and does not try to
modify code or execute data.
In practice, most existing real mode programs do at least one of the things
listed above, rendering them incompatible with 16-bit protected mode.

==== 32-bit protected mode
If the current code segment is a 32-bit segment, the default address and
operand size is 32-bit.

32-bit addressing allows for up to 4 GiB of directly addressable RAM, rather
than 64 kiB, as is the case with 16-bit addressing.
This, along with paging, largely removes the necessity for multiple segments,
as modern operating systems mostly rely on paging, and have one code segment
and one data segment per ring per linear address space, usually having the base
zero.
To a 32-bit user program, segmentation is essentially transparent, and the
address space consists of 4 GiB of flat contiguous memory.

==== Virtual 8086 mode
_Virtual 8086 mode_ was introduced with the 386, and allows the execution of
real mode programs in a virtual machine under a hypervisor in protected mode.

=== System management mode
Introduced with the 386SL and 486SL (CPUs targeting laptops), and included in
the Pentium and subsequent processors, _system management mode_ is mostly
transparent to the operating system.
System management mode is intended for firmware to provide functions, such as
power management, independently from the operating system that is currently
running.

=== Long mode
*Long mode* was introduced with x86-64 and allows software to use 64-bit
address and data.
Linear addresses are now 64-bit, thus allowing for a linear address space of
up to 16 EiB.
The paging scheme restricts this to 48-bit, however, with the remaining bits
being sign extended, thus producing two halves of 128 TiB of "canonical address
space".
An address that complies with this sign extension requirement is said to be in
_canonical form_.
The half starting at zero is called the (canonical) _lower half_.
The half starting at 16 EiB - 128 TiB is called the (canonical) _higher half_.

If 5-level paging (also known as LA57) is enabled, the canonical address space
is extended to 57-bit, thus extending the maximum amount of virtual memory from
256 TiB to 128 PiB.

Much like protected mode, long mode has three sub-modes, depending on the
current code segment.

==== 64-bit mode
If the current code segment is 64-bit, the code is interpreted as 64-bit code
and 64-bit registers may be used.
Many legacy features of protected mode, such as segmentation, are largely
disabled.
CS, DS, ES and SS always have base zero, while FS and GS may have
a non-zero base.
No segment limit checks are performed.

==== Compatibility mode
_Compatibility mode_ (not to be confused with legacy mode) is a sub-mode of
long mode, that allows 16-bit and 32-bit applications to run alongside 64-bit
applications.
Segmentation works like in protected mode, but many features only directly
visible to the operating system, such as paging, system calls, and interrupts,
work as they do in 64-bit mode.
Certain features, such as virtual 8086 protected mode, no longer work under
compatibility mode.

===== 16-bit compatibility mode
If the current code segment is 16-bit, the code will be interpreted as 16-bit
code.
As with 16-bit protected mode, most existing real mode software cannot be run
in 16-bit compatibility mode.

===== 32-bit compatibility mode
If the current code segment is 32-bit, the code will be interpreted as 32-bit
code.
32-bit compatibility mode allows existing 32-bit programs to be run under long
mode.

==== x86 virtualization
Modern x86 processors provide hardware-assisted virtualization.
Intel processors have _VT-x_ (also known as VMX) and AMD processors have
_AMD-V_ (also known as SVM).

== Instruction set and execution model
Each of the major x86 generations introduce major additions to the core
instruction set.

In the context of x86, a _word_ is a 16-bit value, a _dword_ is a 32-bit value,
and a _qword_ is a 64-bit value.footnote:[As is convention elsewhere, a byte is
an 8-bit value and a nibble is a 4-bit value.]

[NOTE]
Cells of tables describing a data structure may be left empty, labeled
"reserved", "0", or "1", in order to indicate this field is reserved.
Software should make no assumption about the value of these fields.
Modifying reserved bits of CPU registers should be avoided.
Memory fields marked as "reserved" should be set to zero.

=== 8086
The 8086 and 8088 have a 20-bit physical address space of 1 MiB of RAM, that
is accessed through two 16-bit values called the _segment_ and _offset_.
The segment is shifted left by 4 bits (i.e. multiplied by 16) and then added to
the offset to obtain the 20-bit physical address.

In addition to regular RAM, there is a 16-bit address space of 65536 byte-sized
I/O ports, that can be accessed through the `in` and `out` instructions.

==== Registers
The 8086 has eight word-sized and eight byte-sized general-purpose registers.
These byte-sized registers are aliases for individual bytes of the word-sized
general-purpose registers AX, BX, CX, and DX.
The byte register AL is an alias for the low byte of AX, the byte register AH
is an alias for the high byte of AX.
Analogous relationships exist between BL, BH, and BX, CL, CH, and CX, and DL,
DH, and DX.
The remaining 16-bit general-purpose registers are SI (source index), DI
(destination index), BP (base pointer), and SP (stack pointer).

In addition to the general purpose registers, there are four word-sized segment
registers: the code segment CS, the data segment DS, the extra segment ES and
the stack segment SS.
There are also two word-sized registers, that are only indirectly accessible to
the programmer: the 16-bit instruction pointer IP and the FLAGS register.

.8086 registers
[%header,cols="6,16*"]
|===
| Register name
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| AX (accumulator) 8+| AH 8+| AL

| CX (counter) 8+| CH 8+| CL

| DX (auxiliary accumulator) 8+| DH 8+| DL

| BX (base address) 8+| BH 8+| BL

| SP (stack pointer) 16+| SP

| BP (base pointer) 16+| BP

| SI (source index) 16+| SI

| DI (destination index) 16+| DI

| IP (instruction pointer) 16+| IP

| FLAGS | 1 | 1 | 1 | 1 | OF | DF | IF | TF | SF | ZF | | AF | | PF | | CF

| ES (extra segment) 16+| ES

| CS (code segment) 16+| CS

| SS (stack segment) 16+| SS

| DS (data segment) 16+| DS
|===

The 8086 has following flags:

Carry flag (CF):: Indicates an arithmetic carry for unsigned operations.
Parity flag (PF):: Is set if the parity of the result of an arithmetic
                   operation is even.
Adjust flag (or auxiliary carry flag, AF):: Indicates a carry out of the first
                                            nibble of an arithmetic operation.
Zero flag (ZF):: Is set if the result is zero.
Sign flag (SF):: Indicates a negative value as the result of a signed
                 arithmetic operation.
Trap flag (TF):: If set, interrupt 1 (see below) is raised on each instruction
                 that is executed.
                 The trap flag is automatically cleared when an interrupt is
                 dispatched.
Interrupt flag (IF):: If cleared, all hardware interrupts are disabled, except
                      for NMI.
                      The interrupt flag is automatically cleared when an
                      interrupt is dispatched.
Direction flag (DF):: Determines the direction of string operations.
                      If it is cleared, the indices (SI or DI) involved are
                      increased.
                      If it is set, the indices are decreased.
Overflow flag (OF):: Is set if a signed arithmetic operation results in an
                     overflow.

==== Instruction modes
Since memory is accessed through a segment address (which is always the value
of one of the segment registers), in addition to an offset (the notation
segment:offset is used), the program counter and stack pointer consist of two
16-bit registers.
The program counter is CS:IP and the stack pointer is SS:SP.

The normal flow of execution is increasing IP.
CS is not automatically incremented if IP exceeds the limit of CS, instead, IP
either wraps around to zero (as is the case on the 8086), or an exception is
raised on later CPUs.

On x86, the stack grows downwards: `push` decreases SP and `pop` increases
SP.
As with the program counter, exceeding the limits of the stack segment does not
result in a change in SS.

Despite having eight general-purpose registers, the 8086 instruction set is not
very orthogonal.
Every 16-bit register has a special role in at least one instruction, examples
include:

* AL is the 8-bit accumulator, and is used to store the quotient of a
  `div byte` instruction.
* AH is used to store the remainder of a `div byte` instruction.
* AX is used to store the quotient of a `div word` instruction.
* BX is used as the table base address for the `xlat` instruction.
* CX is used as a counter for the `loop` instruction.
* DX is used to store the remainder of a `div word` instruction.
* SI is used as the source address for the `movsb` and `movsw` instructions.
* DI is used as the destination address for the `movsb` and `movsw`
  instructions.
* Using BP as the base of the effective address (see below), will result in
  the use of the stack segment.
* SP is the stack pointer.

Every instruction involving memory has a default segment, and most may be
overridden using a *segment override prefix*.
Most memory operands may have a wide variety of indirect addressing modes.
Offsets may be determined through a runtime computation of adding up to three
values:

* *base* - either zero, BX or BP
* *index* - either zero, SI or DI
* *displacement* - a constant value (encoding allows either zero, a
  sign-extended byte, or a word)

The result of the computation is called the *effective address (EA)* (one may
write `[base + index + displacement]` to refer to the corresponding memory
address, or `[segment:base + index + displacement]` when using a segment
override).
The default segment is DS, except when the base is BP, in which case it is SS.

.8086 addressing modes
[%collapsible]
====
|===
| Effective address | Displacement formats | Default segment

| `bx + si + disp` | Zero, byte or word | DS

| `bx + di + disp` | Zero, byte or word | DS

| `bp + si + disp` | Zero, byte or word | SS

| `bp + di + disp` | Zero, byte or word | SS

| `si + disp` | Zero, byte or word | DS

| `di + disp` | Zero, byte or word | DS

| `bp + disp`
| Byte or wordfootnote:[The encoding for displacement zero is used to indicate
  a direct offset.
  This means `[bp\]` is encoded as `[bp+0\]`, and is not shorter than `[bp+1\]`
  (e.g. the encoding for `[si+0\]` is shorter than `[si+1\]`).]
| SS

| `disp` footnote:[As in: direct memory reference.] | Word | DS

| `di + disp` | Zero, byte or word | DS
|===
====

==== Memory models
Since 16-bit segments are limited to 64 kiB, applications may use multiple
segments, meaning that there are multiple ways to organize a program into
memory segments.
These schemes are called *memory models*.
There are six standard memory models, that are widely supported by compilers
and assemblers:

Tiny:: Everything is in a single segment.
Small:: One code segment; one data segment.
Compact:: One code segment; multiple data segments.
Medium:: Multiple code segments; one data segment.
Large:: Multiple code segments; multiple data segments.
Huge:: Single memory range up to 1 MiB (see below).

There exist three types of pointers:
Near pointers:: Word-sized offsets that are used when there is no ambiguity
                regarding the segment.
Far pointers:: Dword-sized segment-offset pairs that are used when there is a
               necessity to specify what segment is used.
Huge pointers:: Similar to far pointers, in that they are dword-sized
                segment-offset pairs, and are used in the huge memory model.

The *huge memory model* takes advantage of the linear relationship between
segment address and segment base in real mode to treat the entire 1 MiB range
as a single memory segment.
This is done through huge pointers, which are essentially far pointers that are
normalized, so the offset is always smaller than 16.
This effectively yields a 20-bit address if the highest 12 bits of the offset
are ignored (since they are always zero due to normalization).
This allows the transparent implementation of arrays larger than 64 kiB.
The stack, however, may not exceed 64 kiB.
Due to relying on real mode segment arithmetic, it does not work in protected
mode.

.8086 memory models
|===
| Memory model | Code pointer type | Data pointer type | Segment registers

| Tiny | Near | Near | CS = DS = ES = SS

| Small | Near | Near | DS = SS

| Compact | Near | Far |

| Medium | Far | Near | DS = SS

| Large | Far | Far |

| Huge | Huge | Huge |
|===

==== Interrupts and exceptions
The 8086 supports 256 types of interrupts.
Interrupts may be caused by hardware, by a CPU exception, or explicitly by
software through the `int` instruction.
When an interrupt is raised, the processor pushes the current state of the
flags register, current code segment, and the offset of the next instruction
to be executed when the interrupted program is resumed.
It then determines the address to jump to using the *interrupt vector table
(IVT)*, a 1 kiB (256 times 4 bytes) table, starting at physical address zero,
consisting of far pointers.

The routine that is called when an interrupt happens is called the *interrupt
service routine (ISR)*.
An ISR may resume the interrupted program through the `iret` instruction.
The 8086 generates following CPU exceptions:

* Division by zero (interrupt 0) occurs when a `div` or `idiv` instruction has
  operand zero or when the quotient does not find into the accumulator.
* Single-step trap (interrupt 1) occurs when the trap flag (see above) is set.
* Debug breakpoint (interrupt 3) is invoked when the (single byte) `int3`
  instruction is executed.
* Overflow (interrupt 4) is invoked when the `into` (interrupt on overflow)
  instruction is executed and the overflow flag is set.

Interrupt 2 is dispatched when a non-maskable hardware interrupt, or NMI,
occurs.
Intel reserved the first 32 interrupts for future use (i.e. additional CPU
exceptions).
IBM did not heed that recommendation, causing compatibility issues.

.Call and interrupt stack
[%collapsible]
====
|===
| Address | Near call | Far call | Interrupt

| `sp + 6` .3+| Caller stack .2+| Caller stack | Caller stack

| `sp + 4` | FLAGS

| `sp + 2` | CS | CS

| `sp` | IP | IP | IP
|===
====

=== 80186
The 186 and 188 implement all of the new 286 instructions that are not related
to protected mode.
New CPU exceptions, such as the invalid opcode exception, were also introduced.
These extensions consist of:

* immediate modes for `imul`, `push` and the shift and roll instructions
* string operations on I/O ports
* `bound` instruction and the bounds range exceeded exception (interrupt 5)
* shorthands `enter`, `leave`, `pusha`, `popa`
* invalid opcode (interrupt 6) and coprocessor not present exceptions
  (interrupt 7)

[NOTE]
The 186 and 188 are still very similar to the 8086 and 8088.
No new registers are added, and the behavior of `push sp` and `pushf` are the
same as with the 8086.

=== 80286
The introduction of protected mode with the 286 is a major change to the x86
ISA.
Protected mode introduces new data structures, mechanisms for virtual memory,
memory protection, hardware task switching, and the ability to access a 24-bit
physical address space of 16 MiB.

Hardware memory protection is primarily enforced through *protection rings*.
Ring 0 is the most privileged; Ring 3 is the least privileged.
Rings with lower number (more privilege) are referred to hereafter as _lower_;
rings with higher number (less privilege) are referred to hereafter as _higher_
(i.e. the numeric relation).

.286 registers
[%collapsible]
====
[%header,cols="3,16*"]
|===
| Register
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| AX 8+| AH 8+| AL

| CX 8+| CH 8+| CL

| DX 8+| DH 8+| DL

| BX 8+| BH 8+| BL

| SP 16+| SP

| BP 16+| BP

| SI 16+| SI

| DI 16+| DI

| IP 16+| IP

| FLAGS
| 0 | *NT* 2+| *IOPL* | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| MSW
| 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | *TS* | *EM* | *MP* | *PE*

| ESfootnote:[Hidden descriptor caches are omitted.] 16+| ES (visible selector)

| CS 14+| (visible CS selector) 2+| CPL

| SS 14+| (visible SS selector) 2+| CPL

| DS 16+| DS (visible selector)

| TR 16+| TR (visible selector)

| LDTR 16+| LDTR (visible selector)

.3+| GDTR 8+| 8+| Base (23:16)
16+| Base (15:0)
16+| Limit

.3+| IDTR 8+| 8+| Base (23:16)
16+| Base (15:0)
16+| Limit
|===
====

==== Segmentation
There is no longer a linear relationship between segment address and segment
base.
Instead, the properties of segments are determined by *segment descriptors*.
The values of the segment registers are now interpreted as *segment selectors*.
The segment selector is essentially an index to one of the two segment
descriptor tables: the *Global Descriptor Table (GDT)* and the *Local
Descriptor Table (LDT)*.

As the names suggest, the GDT contains segment descriptors for every task, and
the LDT contains segment descriptors for a specific task.
Thus, each task can access a global virtual address space, in addition to
having its own private address space.

The IVT is replaced by the *Interrupt Descriptor Table (IDT)*.
The IDT has an identical format to the GDT and LDT, but instead of referring to
entries in the IDT through segment selectors, each entry in the IDT corresponds
to an interrupt type (i.e. the first entry corresponds to interrupt 0, the
second to interrupt 1, and so on), with the descriptor defining the ISR to be
used.

The 286 includes facilities for managing multiple tasks.
The state of a task is stored in a *Task State Segment (TSS)*.
Both LDT and TSS are segments, much regular segments, and have a corresponding
entry in the GDT.

.Segment selector format
[cols="16*"]
|===
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

13+| Index | TI 2+| RPL
|===

Index:: The index within the descriptor table.
TI:: The table indicator.
     Zero for GDT; one for LDT.
RPL:: The requested privilege level.

Descriptor tables are arrays of 8-byte segment descriptors, that reside in RAM.
The first entry of the GDT is reserved.
Selectors referring to this entry are so-called _null selectors_, and may be
used as placeholder values for DS and ES, but not CS and SS.
Any attempt to access memory through a null selector results in a general
protection fault.
The IDT may only contain task, interrupt, or trap gates.

.286 segment descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Reserved

| +32 | P 2+| DPL | S 4+| Type 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

Limit:: The highest allowed offset address (inclusive).
        This means a limit of 65535 indicates a segment of 65536 bytes; a limit
        of zero indicates a segment of one byte.
        For expand-down segments, it is the lowest allowed offset address minus
        one (i.e. exclusive), with the maximum allowed offset being 65535.
        A limit of 65535 indicates an empty segment; a limit of zero indicates
        a segment of 65535 bytes.
        If the present bit is not set, this field may be used for other data.
Base:: Physical address of the first byte of the segment (equivalent to offset
       zero).
       For expand-down segments, defines the first byte after the last byte
       of the segment (also effectively equivalent to offset zero).
       If the present bit is not set, this field may be used for other data.
Type:: Meaning depends on the whether it is a system segment descriptor.
S flag:: Zero for system segment descriptors; one for code or data descriptors.
DPL:: Descriptor privilege level.
Present bit (P):: Zero indicates the segment is invalid (intended for operating
                  systems to implement swapping).

The fifth byte of a descriptor (i.e. the type, S, DPL, and P fields) is known
as the *access byte*.

.Code and data segment types
[cols="4*"]
|===
| 43 | 42 | 41 | 40

| X | CE | RW | A
|===

Executable bit (X):: One for code segments; zero for data segments.
Conforming/expand-down bit (CE):: For code segments: zero for nonconforming
                                  code segments; one for conforming code
                                  segments.
                                  For data segments: zero for expand-up data
                                  segments; one for expand-down data segments.
Readable/writable bit (RW):: For code segments: zero for execute-only code
                             segments; one for readable code segments.
                             For data segments: zero for read-only data
                             segments; one for writable data segments.
Accessed bit (A):: This bit is set when a segment is accessed.
                   This way the operating system can keep track of which
                   segments were used.

.286 system segment types
[cols="4*,5,6"]
|===
| 43 | 42 | 41 | 40 | Segment type | Descriptor tables

| 0 | 0 | 0 | 0 | Reserved | None

| 0 | 0 | 0 | 1 | Available TSS | GDT only

| 0 | 0 | 1 | 0 | LDT descriptor | GDT only

| 0 | 0 | 1 | 1 | Busy TSS | GDT only

| 0 | 1 | 0 | 0 | Call gate | All

| 0 | 1 | 0 | 1 | Task gate | GDT, LDT

| 0 | 1 | 1 | 0 | Interrupt gate | IDT only

| 0 | 1 | 1 | 1 | Trap gate | IDT only

| 1 | x | x | x | Reserved | None
|===

Gates have a different format to other segment descriptors (i.e. code, data,
LDT, and TSS segments).

.16-bit gate descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Reserved

| +32 | P 2+| DPL | S 4+| Type 3+| Reserved 5+| Word count

| +16 16+| Segment

| +0 16+| Offset
|===

Offset:: Target offset (unused by task gate).
Segment:: Target segment selector.
          Must point to code segment for call, interrupt, and trap gates, and
          to a TSS for task gates.
          The RPL field is ignored by call, interrupt, and trap gates.
Word count:: Amount of words to push.
             Call gates only; reserved for all other kinds of gate.

In addition to the visible 16-bit selectors, all segment registers have an
invisible _segment descriptor cache_,footnote:[This also applies to real mode,
where the 8086 behavior is emulated by updating the base value with the
segment address times 16, instead of looking up a descriptor table.
Other values, such as the limit are constant and are set to initial values,
in order to replicate 8086 behavior.
This means they can be changed by switching to protected mode, loading the
segment registers with new descriptors, and switching back to real mode.
This is what unreal mode is.]
which contains the segment descriptor corresponding to the selector, so that
the CPU does not need to constantly look up the descriptor tables.

The location of the GDT, LDT, IDT, and TSS are indicated by the _GDT Register
(GDTR)_, _LDT Register (LDTR)_, _IDT Register (IDTR)_ and _Task Register (TR)_
respectively.
The LDTR and TR are similar to regular segment registers, as they store a
16-bit selector, visible to the programmer, and a hidden descriptor cache.
The LDTR can be set using the `lldt` instruction, and the TR can be set using
the `ltr` instruction.
Both of these instructions accept a 16-bit direct operand (register or
memory), containing a selector pointing to the corresponding descriptor in the
GDT.

The GDT and IDT are not segments. and the GDTR and LDTR do not have the visible
16-bit selector part.
The GDTR and LDTR are effectively 48-bit registers and may be set using the
`lgdt` and `lidt` instructions respectively, which take a pointer to a 6 byte
structure, called a _pseudo-descriptor_, that is similar to a regular segment
descriptor, due to having base and limit fields.

.286 pseudo-descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +32 8+| Reserved 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

==== Memory protection
Protected mode introduces new memory protection mechanisms.
In order to understand these, one must first understand the different privilege
levels that are taken into account:

* The __current privilege level (CPL)_ is the privilege level of the current
  task.
  It corresponds to the RPL field of the segment selectors stored in CS and
  SS (i.e. bits 0 and 1 of the visible 16-bit values of CS and SS).
* The __descriptor privilege level (DPL)__ is the privilege level of the
  segment being accessed (determined in the segment descriptor).
* The __requested privilege level (RPL)__ is the privilege level given by the
  segment selector (i.e. bits 0 and 1 of the segment selector).
* The __effective privilege level (EPL)__ is the maximum of the CPL and RPL.
* The __I/O privilege level (IOPL)__ is a value in the FLAGS register, that
  determines the highest CPL allowed to do direct I/O (`in`, `out`, `ins` and
  `outs`), to set and clear the interrupt flag (`cli` and `sti`) and to use the
  `lock` prefix within the current task. 

[NOTE]
Trying to set IF indirectly through `popf` or `iret` with NT cleared, results
in no change of IF, if the CPL is higher than the IOPL.
The IOPL also remains unchanged after `popf` or `iret` with NT cleared, unless
the CPL is zero.
A task switch can always modify any flag.

Certain instructions, such as `lgdt`, can only be used if the CPL is 0.
There are also forms of protection independent of the privilege levels, such as
checking segment limits, restricting writing a code segment, or read-only data
segment, and restricting reading an execute-only code segment through a CS
override.

Before accessing a segment, a segment register must first be set.
This CPU means the can perform most privilege checks at that point, instead of
every time memory is read or written.
The particular privilege level checks depends on how the segment register is
set and the type of descriptor the selector points to.

DS, ES, and SS can be changed directly through `mov` and `pop`.
In general, these registers must be loaded with data segments or readable code
segments with the DPL higher or equal to the EPL.
However, different rules may apply (see table, e.g. SS must always point to a
writable segment with DPL equal to CPL).

LDTR and TR can only be changed explicitly in Ring 0 using the `lldt` and
`ltr` instructions.
The LDTR must be loaded with a selector pointing to a valid LDT descriptor in
the GDT.
The TR must be loaded with a selector pointing to a valid TSS descriptor in the
GDT.

.Conditions for successful update of segment registers
[cols="8"]
|===
.2+h| Mechanism
7+h| Target

| Data segment
| Nonconforming code segment
| Conforming code segment
| Call gate to nonconforming code segment
| Call gate to conforming code segment
| TSS or task gate
| Interrupt or trap gate

| Updating DS or ES
2+| `DPL >= EPL` and readable
| Readable
4+| Disallowed

| Updating SS
| `DPL == RPL == CPL` and writable
6+| Disallowed

| Updating CS through far `jmp`
.3+| Disallowed
.2+| `DPL == CPL && RPL \<= CPL`
.2+| `DPL \<= CPL`
| `gate DPL >= gate EPL && target DPL == CPL`
| `gate DPL >= gate EPL && target DPL \<= CPL`
.2+| `gate DPL >= tss EPL`
1+| Disallowed

| Updating CS through far `call` or `int`
2+| `gate DPL >= gate EPL && target DPL \<= CPL`
1+| `gate DPL >= CPL && target DPL \<= CPL` footnote:[Gate DPL is not checked
    if interrupt not caused by `int` instruction.]

| Updating CS through `retf` or `iret`
2+| `RPL >= CPL`
4+| Disallowed
|===

Segment registers may be changed implicitly through instructions (and
interrupts) that pass control flow to another code segment.
A control transfer to a nonconforming code segment results in the CPL being set
to the DPL of the incoming code segment.
A control transfer to a conforming code segment results in no change in DPL.
Not just CS and IP may be changed as a result of a transfer to another code
segment.
If the operation results in a change in CPL, the stack is also switched
(meaning a change in SS and SP).

Control transfers may also target a TSS, instead of a code segment, resulting
in a task switch, with the task described by the TSS being resumed, and the
state of the outgoing task being saved in the TSS of the outgoing task.
This results in most CPU registers (including LDTR) being changed and the
incoming task resuming at the state described by its TSS (including the CPL,
which is stored in the RPL field of CS and SS).

Operations that result in a change of code segment include far `jmp` and
`call`, which provide a far pointer, or an interrupt (that can be caused by an
`int` instruction), which provides an interrupt vector.
Either way, these point to an unique segment descriptor.
The segment selector of the far pointer points to a segment descriptor in the
GDT or LDT, while the interrupt vector points to a segment descriptor in the
IDT.

`jmp` and `call` may target a code segment, call gate, or task gate.
A `jmp` instruction may not result in a change of CPL (violations of this, i.e.
through targeting a nonconforming segment with DPL not equal to CPL, result in
a general protection fault).

* If a code segment is targeted, control is transferred to that code segment at
  the offset provided as the operand of the instruction (assuming no protection
  violations or other faults).
  As with `jmp` instructions, a `call` instruction directly targeting a code
  segment may not result in a change of CPL (i.e. it must be a "intra-level"
  call).
  `call` behaves similar to real mode, in the sense that it pushes a far
  pointer to stack for `retf` to pop.

* If a call gate is targeted, control is transferred to the code segment at the
  offset provided by the call gate descriptor.
  The offset provided by the instruction is ignored.
  A `call` to a call gate allows control to be transferred from less privileged
  code to more privileged code (i.e. the CPL gets lower, "inter-level call").
  If a change in CPL occurs, a stack switch to the stack corresponding to the
  new protection ring, as defined in the TSS, occurs.
  If a stack switch occurs, the processor first pushes SS and SP, then copies
  the amount of words given in the word count descriptor field to the new stack
  and then pushes CS and IP.
  Note the call gate has following properties:

  . It is transparent to the application.
    The application simply does `jmp` or `call` as if it was a code segment.
  . The word count mechanism allows for transparent passing of parameters on
    the stack.
  . The offset operand of the `jmp` or `call` instruction is ignored.
    This prevents an application from entering the middle of a procedure, or a
    procedure it should not enter.
  . The procedure can transparently return via `retf`.

* If a TSS or task gate is targeted, the task described by the TSS (or the TSS
  pointed to by the selector in the task gate) is resumed.
  For a procedure invoked via a TSS or task gate to properly return, it must
  use `iret`, not `retf`.

.Call gate stack
[%collapsible]
====
|===
| Address | Intra-level | Inter-level

| `sp + 12` .3+| Caller stack
| = SSn:SPnfootnote:[Where _n_ is the target CPL.]

| `sp + 10` | SS

| `sp + 8` | SP

| `sp + 6` | Parameter 2 | Parameter 2

| `sp + 4` | Parameter 1 | Parameter 1

| `sp + 2` | CS | CS

| `sp` | IP | IP
|===
====

The actions of the `retf` instruction depend on the segment selector of the
far return pointer on the stack.
The selector part of the pointer must point to a valid code segment.
The RPL of that selector indicates the CPL of the caller.
If the RPL equals the CPL, no CPL change is necessary and the `retf`
instruction behaves like the `retf` instruction in real mode.
Otherwise, a stack switch occurs by restoring the caller SP and SS on the
callee stack.
In addition `retf` checks the DPL of DS and ES and sets them to null selectors
if they are lower than the caller CPL.

.16-bit TSS structure
[%collapsible]
====
[%header,cols="5,16*"]
|===
| Byte offset
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| 0 16+| Previous TSS selector backlink

| 2 16+| SP for Ring 0 (SP0)

| 4 16+| SS  for Ring 0 (SS0)

| 6 16+| SP for Ring 1 (SP1)

| 8 16+| SS  for Ring 1 (SS1)

| 10 16+| SP for Ring 2 (SP2)

| 12 16+| SS  for Ring 2 (SS2)

| 14 16+| IP

| 16 16+| FLAGS

| 18 16+| AX

| 20 16+| CX

| 22 16+| DX

| 24 16+| BX

| 26 16+| SP

| 28 16+| BP

| 30 16+| SI

| 32 16+| DI

| 34 16+| ES

| 36 16+| CS

| 38 16+| SS

| 40 16+| DS

| 42 16+| LDTR
|===
====

The RPL (and EPL) mechanism serves to prevent privilege escalation (i.e. a
less privileged program accessing privileged memory indirectly through a system
call, by passing a pointer to that portion of memory).
When less privileged code passes a pointer to more privileged code, the pointer
can be tagged using the `arpl` instruction (which takes the maximum of the CPL
of the callee with the current RPL of the selector).
This means pointers are tagged with the CPL of the original caller.

For example, a procedure with CPL 3 passes a selector with RPL 0 pointing to a
descriptor with DPL 2 to a procedure with CPL 2, that in turn calls a procedure
with CPL 0.
When the procedure with CPL 2 is invoked, it executes `arpl` and sets the RPL
of the selector to 3 (which is the maximum of CPL 3 and RPL 0).
The procedure with CPL 0 also invokes `arpl`, and the RPL of the selector
remains 3 (which is the maximum of CPL 2 and RPL 3).
Throughout all the stages, the EPL remains 3, which means a general protection
fault will be raised when accessing this pointer, even in Ring 0, since the EPL
is larger than the DPL.

==== Interrupts and task switching
Interrupts behave in a similar way to the `call` instruction.
The effect depends on the corresponding IDT entry:

* If the target is an interrupt or trap gate, it behaves in a similar way to a
  call gate being invoked by a `call` instruction.
  The main difference is that no parameters from the caller stack are copied if
  a privilege change occurs.
  Instead, the FLAGS register is always pushed, and the trap flag is cleared
  (in a similar fashion to interrupts in real mode).
  The only difference between an interrupt gate and a trap gate is that an
  interrupt gate clears the interrupt flag (much like real mode), while a trap
  gate does not.
* If the target is a task gate, it resumes the task described by the TSS
  pointed to by the task gate, much like a `call` instruction.
  The interrupt flag of the incoming task is cleared.

In order to keep track of what interrupts and far calls were serviced by a task
gate, the CPU maintains the _nested task (NT) flag_.
Whenever a task switch due to an interrupt and call occurs, the NT flag of the
new task is set and the previous TSS backlink of the incoming task is filled
with the TSS selector of the outgoing task.
A task switch due to a jump clears the NT flag of the incoming task.

In addition, each TSS descriptor maintains a flag indicating whether the task
is "available" or "busy".
The currently executing task is always busy, as are previous callers in the
caller chain.
Only an available task may be resumed through a task gate; only a busy task may
be resumed through `iret`.
Entering a task gate results in the incoming task becoming busy.
While a `jmp` instruction causes the outgoing task to become available, `call`
instructions and interrupts result in the outgoing task remaining busy.
`iret` results in the callee becoming available once again.

The behavior of `iret` depends on the NT flag.
If the NT flag is cleared, `iret` behaves in a similar way to `retf`, except
that the FLAGS register (which was pushed on to the stack) is restored.
The IOPL is only changed if the callee is at Ring 0.
If the NT flag is set, indicating an interrupt or call to a task gate, `iret`
causes a task switch to the task pointed to by the selector in the previous
TSS backlink (i.e. the caller task).
The NT flag of the callee (outgoing) task is subsequently cleared.

.Interrupt and trap gate stack
[%collapsible]
====
[%header,cols="5"]
|===
| Address
| Intra-level, +
  no error code
| Intra-level, +
  error code
| Inter-level, +
  no error code
| Inter-level, +
  error code

| `sp + 14` .4+| Caller stack .3+| Caller stack | | = SSn:SPn

| `sp + 12` | = SSn:SPn | SS

| `sp + 10` | SS | SP

| `sp + 8` | FLAGS | SP | FLAGS

| `sp + 6` | FLAGS | IP | FLAGS | IP

| `sp + 2` | IP | CS | IP | CS

| `sp` | CS | Error code | CS | Error code
|===
====

The 286 introduces a plethora of new exceptions.
Protected mode exceptions may push a 16-bit error code on top of the stack,
usually indicating a descriptor entry related to the exception (the exact
descriptor entry depends on the exact kind of exception).
The error code may also be zero.

.Error code format
[cols="16*"]
|===
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

13+| Index 2+| TI | I | EX
|===

Index:: The index within the descriptor table.
Table indicator (TI):: Zero for GDT; one for LDT.
Interrupt (I):: Zero for GDT or LDT; one for IDT.
External (EX): Set if exception caused by external interrupt.

Exceptions are classified into three types:footnote:[This terminology was
introduced with the 386.
The 286 manual differentiates between restartable (faults and traps) and
non-restartable exceptions (aborts).]

Fault:: Indicates a non-critical error has happened.
        These errors can be corrected and the program can be restarted at the
        faulting instruction.
Trap:: Traps allow a program to be restarted at the instruction following the
       trapping instruction.
Abort:: Aborts cannot be restarted reliably and indicate a critical error.

.286 exceptions
|===
| Vector | Name | Type | Class | Error code

| 0
| Divide by zero
| Fault
| Contributoryfootnote:[This is not a "protection violation", so would be
  considered benign, according to the 286 manual.]
| No

| 1
| Debug
| Trapfootnote:[Debug features in the 386 and later may dispatch a fault, rather
  than a trap, as is the case for exceptions caused by the trap flag.]
| Benign
| No

| 3 | Breakpoint | Trap | Benign | No

| 4 | Overflow | Trap | Benign | No

| 5 | Bounds range exceeded | Fault | Benign | No

| 6 | Invalid opcode | Fault | Benign | No

| 7 | Coprocessor not present | Fault | Benign | No

| 8 | Double fault | Abort | Benign | Yesfootnote:[Always zero.]

| 9
| Coprocessor segment overrunfootnote:[486 and later never dispatch this
exception.]
| Abort
| Contributory
| No

| 10
| Invalid TSSfootnote:[May not be restartable on 386 and 486 if it happens when
  dispatching an interrupt.]
| Fault
| Contributory
| Yes

| 11 | Segment not present | Fault | Contributory | Yes

| 12 | Stack fault | Fault | Contributory | Yes

| 13
| General protection fault
| Faultfootnote:[With the 286, a segment limit overrun during a string
  operation, a general protection fault during a coprocessor segment overrun,
  and writing into a read-only segment through `adc`, `sbb`, `rcl`, or `rcr`
  are not restartable.
  On later processors, a general protection fault is always restartable, but if
  it was caused while dispatching an interrupt, the interrupt may be lost.]
| Contributory
| Yes

| 16
| Coprocessor errorfootnote:[Motherboards may wire this interrupt somewhere
  else.
  XT-class PCs wired the FPU error pin to NMI.
  The IBM AT and most AT-class machines wire this to IRQ13, with the BIOS then
  redirecting it to NMI for compatibility.
  Some manufacturers wire it to NMI or to interrupt 16, causing compatibility
  problems.
  CPUs with integrated FPUs (i.e. 486 and later) have a flag on whether to
  route the instruction externally through the motherboard, or whether to use
  interrupt 16 internally.]
| Fault
| Benign
| No
|===

When an exception occurs while an exception handler is being dispatched, the
result depends on the kind of exception.
It may either handle them serially, dispatch a *dobule fault*, or enter a
*triple fault*.
When a triple fault occurs, the processor shuts down.
Depending on the motherboard, this usually causes the computer to be rebooted.

Exceptions can be divided into four relevant classes: _benign_, _contributory_,
_page fault_ (introduced with the 386) and
_double fault_.footnote:[The 286 manual does not use this terminology.
Instead, it differentiates between protection violation and other (instead of
contributory and benign).]

.Double exception handling
[%collapsible]
====
[cols="4*"]
|===
.2+h| First exception
3+h| Second exception

| Benign
| Contributory
| Page fault

| Benign
| Handled serially
| Handled serially
| Handled serially

| Contributory
| Handled serially
| Double fault
| Handled serially

| Page fault
| Handled serially
| Double fault
| Double fault

| Double fault
| Handled serially
| Triple fault
| Triple fault
|===
====

==== Machine Status Word
The 286 also introduced a new 16-bit register called the _Machine Status Word
(MSW)_, which can only be directly modified in Ring 0 through the `lmsw` and
`clts` instructions.

Protection enabled (PE):: Set for protected mode; clear for real mode.
                          May not be cleared once set on a 286 (later
                          processors allow returning back to real mode).
Monitor coprocessor (MP):: Raises coprocessor not present exception (interrupt
                           7) on `wait`, if MP _and_ TS are set.
                           Should be set if a physical coprocessor is present
                           (i.e. the results become available asynchronously).
Emulate coprocessor (EM):: Raises coprocessor not present exception on `esc`
                           (i.e. on every floating-point instruction) if set.
                           Intended for emulating an FPU if a physical one is
                           not present.
Task switched (TS):: Raises coprocessor not present exception on `esc` if set.
                     Automatically set when task is switched, so that the
                     operating system is able to switch the x87 context for
                     tasks using floating-point instructions.
                     May be cleared again via `clts`.

MP, EM, and TS also affect most MMX, 3DNow!, and SSE instructions on later
CPUs.

=== i386
The 386 introduced 32-bit extensions, paging, virtual 8086 mode, and the
ability to return to real mode, in addition to new instructions and operand
modes.
It also allows software to change the base and limit of the real mode IVT
through the IDTR.

==== 32-bit registers and addressing
The 386 expanded many registers to 32-bit registers.
These new dword-sized registers have the corresponding word-sized register
aliased to its lower word.
The new registers have an "e" prefix, to differentiate them from their 16-bit
counterpart.
For example, EAX is a 32-bit register, with AX aliasing to the lower word.
Similarly EBX, ECX, EDX, ESI, EDI, EBP, ESP, EIP and EFLAGS were added.

Segment registers and selectors remain word-sized, however, offset sizes are
expanded to 32-bit, yielding a 48-bit logical address.
Two new data segment registers, similar to DS and ES, that can be used with
the corresponding segment override prefix, were introduced: FS and GS.

.386 registers
[%collapsible]
====
[%header,cols="3,32*"]
|===
| Register
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| EAX 16+| (EAX) 8+| AH (AX) 8+| AL (AX)

| ECX 16+| (ECX) 8+| CH (CX) 8+| CL (CX)

| EDX 16+| (EDX) 8+| DH (DX) 8+| DL (DX)

| EBX 16+| (EBX) 8+| BH (BX) 8+| BL (BX)

| ESP 16+| (ESP) 16+| SP

| EBP 16+| (EBP) 16+| BP

| ESI 16+| (ESI) 16+| SI

| EDI 16+| (EDI) 16+| DI

| EIP 16+| (EIP) 16+| IP

| EFLAGS
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | *VM* | *RF*
| 0 | NT 2+| IOPL | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| CR0
| *PG* | | | | | | | | | | | | | | |
| | | | | | | | | | | | *ET* | TS | EM | MP | PE

| CR2 32+| Page fault linear address

| CR3 20+| Page Directory Base Register (PDBR)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0

| DR0 32+| Breakpoint 0 linear address

| DR1 32+| Breakpoint 1 linear address

| DR2 32+| Breakpoint 2 linear address

| DR3 32+| Breakpoint 3 linear address

| DR6
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
| *BT* | *BS* | *BD* | 0 | 0 | 0 | 0 | 0
| 0 | 0 | 0 | 0 | *B3* | *B2* | *B1* | *B0*

| DR7
2+| *LEN3* 2+| *R/W3* 2+| *LEN2* 2+| *R/W2*
2+| *LEN1* 2+| *R/W1* 2+| *LEN0* 2+| *R/W0*
| 0 | 0 | 0 | 0 | 0 | 0 | *GE* | *LE*
| *G3* | *L3* | *G2* | *L2* | *G1* | *L1* | *G0* | *L0*

| ESfootnote:[Hidden descriptor caches are omitted.]
16+| 16+| ES (visible selector)

| CS 16+| 14+| (visible CS selector) 2+| CPL

| SS 16+| 14+| (visible SS selector) 2+| CPL

| DS 16+| 16+| DS (visible selector)

| FS 16+| 16+| FS (visible selector)

| GS 16+| 16+| GS (visible selector)

| TR 16+| 16+| TR (visible selector)

| LDTR 16+| 16+| LDTR (visible selector)

.2+| GDTR 32+| Base 16+| 16+| Limit

.2+| IDR 32+| Base 16+| 16+| Limit
|===
====

In addition to adding 32-bit variants to certain instructions (such as adding
`lodsd` to complement `lodsw` and `lodsb`), the 386 introduced new instructions
and instruction modes, in order to make the instruction set more orthogonal.
For example, the `lss`, `lfs`, and `lgs` instructions, in addition to the
existing `lds` and `les` instructions, new modes for `imul`, and near
conditional jumps (in addition to existing short conditional jumps) were added.
Completely new instructions were also added, such as instructions to sign
extend and zero extend smaller registers into larger registers, `movsx` and
`movzx`.

The 386 decides whether to use 32-bit or 16-bit registers based on the current
code segment.
A 32-bit code segment interprets instructions as operations on 32-bit and
8-bit registers and memory locations and uses 32-bit offsets.
A 16-bit code segment interprets instructions as operations on 16-bit and
8-bit registers and memory locations and uses 16-bit offsets, in the same way
as previous 16-bit processors of the x86 line.
16-bit operands and addresses can be used in a 32-bit code segment and vice
versa using the *operand size prefix* and *address size prefix*.

32-bit effective addresses are significantly more orthogonal than their 16-bit
counterparts.
As with 16-bit addresses, 32-bit addresses may have a base, an index, and a
displacement.
In addition, a *scale* may be added, that is multiplied with the index.

* base - any 32-bit general-purpose register (EAX, EBX, ECX, EDX, ESI, EDI,
  EBP, ESP)
* index - any 32-bit general-purpose register, except ESP (EAX, EBX, ECX, EDX,
  ESI, EDI, EBP)
* scale - 1, 2, 4 or 8
* displacement - zero, 8-bit sign extended value or 32-bit value

Following combinations are allowed:

* `displacement` alone
* `base` alone
* `base + displacement`
* `index * scale + displacement`
* `base + index + displacement`
* `base + index * scale + displacement`

The default segment is DS, except if the base is EBP or ESP, in which
case the default segment is SS.

==== 32-bit segmentation
In order to deal with 32-bit addresses and the extended 32-bit physical address
space of 4 GiB, the 386 introduces backwards-compatible changes to
segmentation.

.386 segment descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 8+| Base (31:24) | G | DB | 0 | A 4+| Limit (19:16)

| +32 | P 2+| DPL | S 4+| Type 8+| Base (23:16)

| +16 16+| Base (15:0)

| +0 16+| Limit (15:0)
|===

Limit:: The Limit field is extended from 16-bit to 20-bit, allowing a limit of
        up to 1 MiB (or 4 GiB using the G-flag).
Base:: Extended to 32-bit.
Available (A):: Available for use by the operating system.
DB flag:: Set for 32-bit segment; clear for 16-bit segment.
          Called the D flag for code segments and the B flag for data segments.
          Meaning depends on type of segment:
          * For a code segment, it defines the default operand and address
            size.
          * For a stack segment, it defines the size of the stack pointer (i.e.
            whether to use just SP or all of ESP for stack operations).
          * For a expand-down segment, it defines the upper bound.
            16-bit expand-down segments have an upper bound of 0xFFFF.
            32-bit expand-down segments have an upper bound of 0xFFFFFFFF.
Granularity flag (G):: If set, limit is given in 4 kiB units, rather than units
                       of one byte.
                       The effective limit is `limit * 4096 + 4095`.
                       Allows for segments of up to 4 GiB.

.New 386 system segment types
[cols="4*,5,6"]
|===
| 43 | 42 | 41 | 40 | Segment type | Descriptor tables

| 1 | 0 | 0 | 1 | Available 32-bit TSS | GDT only

| 1 | 0 | 1 | 1 | Busy 32-bit TSS | GDT only

| 1 | 1 | 0 | 0 | 32-bit call gate | All

| 1 | 1 | 1 | 0 | 32-bit interrupt gate | IDT only

| 1 | 1 | 1 | 1 | 32-bit trap gate | IDT only
|===

Aside from the new 32-bit segments and gates, 386 segmentation fundamentally
works the same as on the 286.
Even the behavior of the stack for 32-bit calls and interrupts works
essentially the same, except that 32-bit registers are pushed, instead of
16-bit registers, and 16-bit selectors and error codes are padded with an extra
high word, in order to become dword-aligned.
The bit width of calls and interrupts is determined by the operand size for
calls directly targeting code segments, and by the type of gate for calls and
interrupts through gates.

.32-bit gate descriptor
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +48 16+| Offset (31:16)

| +32 | P 2+| DPL | S 4+| Type 3+| Reserved 5+| Dword count

| +16 16+| Segment

| +0 16+| Offset (15:0)
|===

Thus, 16-bit and 32-bit segments and gates can be largely mixed.
However, the size of the return instructions must match the size of the call
instructions and a 16-bit call from a 32-bit segment will truncate EIP.
For a 16-bit call to work as expected, it must be called from the first 64 kiB
of a segment, and can only target the first 64 kiB.

The `lgdt` and `lidt` instructions work identically to the 286, except that the
reserved byte is now used to extend the base address field to 32 bits.

.386 pseudo-descriptor format
[cols="3,16*"]
|===
| Offset | 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| +32 16+| Base (31:16)

| +16 16+| Base (15:0)

| +0 16+| Limit
|===

It is not recommended to mix 16-bit and 32-bit task state segments, due to
unintended side-effects of missing fields.
In particular, a 32-bit TSS stores the state of CR3 (i.e. the Page Directory
Base Register PDBR) and the new general-purpose registers introduced with the
386.

.32-bit TSS structure
[%collapsible]
====
[%header,cols="5,32*"]
|===
| Byte offset
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| 0
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| Previous TSS backlink

| 4 32+| ESP0

| 8
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| SS0

| 12 32+| ESP1

| 16
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| SS1

| 20 32+| ESP2

| 24
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| SS2

| 28 32+| CR3 (PDBR)

| 32 32+| EIP

| 36 32+| EFLAGS

| 40 32+| EAX

| 44 32+| ECX

| 48 32+| EDX

| 52 32+| EBX

| 56 32+| ESP

| 60 32+| EBP

| 64 32+| ESI

| 68 32+| EDI

| 72
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| ES

| 76
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| CS

| 80
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| SS

| 84
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| DS

| 88
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| FS

| 92
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| GS

| 96
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
16+| LDTR

| 100 16+| I/O map base
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | T

| 104 32+| Shadow stack pointer
|===
====

I/O map base:: Base offset the _I/O permission bitmap_ in the TSS.
               This allows code running at a CPL higher than the IOPL to have
               limited access to I/O.
               In particular, each bit corresponds to an I/O port.
               If the bit is cleared, code at any CPL may access that I/O port.
               The TSS does not need to contain a complete I/O port bitmap,
               bits beyond the limit of the TSS are treated as being set,
               thereby preventing unprivileged access to the corresponding
               ports.footnote:[Word or dword I/O to unaligned ports may cross a
               byte boundary, meaning two bytes need to be loaded.
               Thus it is recommended to have an extra byte after the highest
               I/O port that is accessed, with numerical value 255.]
T flag (T):: Will raise a debug trap (interrupt 1) after switching to the task,
             but before executing an instruction, when set.
Shadow stack pointer (SSP):: Not present in 386, but included her for
                             completeness.
                             Only available on newer CPUs with control-flow
                             enforcement technology (CET).

==== Paging
The 386 added support for paging as an extra translation layer, in addition to
segmentation.
With paging enabled, segments are not contiguous ranges in physical address
space, but rather contiguous ranges in _linear address space_.
In particular, the base of segments is treated as a _linear address_, rather
than a physical address.
Segmentation translates a _logical address_, consisting of a 16-bit segment
address and a 32-bit offset, to a 32-bit linear address (i.e. segment bases are
no longer physical addresses, but linear addresses).
Paging is responsible for converting this linear address to a physical address.

This is achieved by dividing both linear and physical 4 GiB address spaces
into 1048576 aligned pages of 4096 bytes.
Paging maps pages of physical memory to certain spots in virtual memory.
This effectively creates a flat linear address space that is isolated from
physical memory, allowing for greater isolation of software.

Protected mode segmentation allows for a similar degree of isolation.
Segments, however, need to be contiguous and have variable size.
Pages have fixed size and are invisible to application programs, allowing for
memory to be arbitrarily fragmented and swapped out in chunks of 4096 bytes.

Entries in the translation table are 32-bit, so instead of having a single page
table of 2 MiB (more RAM than many systems had at the time), the 386 employs a
two-level paging system.
The root page table is the *page directory (PD)*, which has _page directory
entries (PDEs)_ pointing to individual *page tables (PT)*, which consists of
_page table entries (PTEs)_ pointing to the physical base address of individual
pages.

Both of these tables occupy 4 kiB, and thus have 1024 entries.
This means each page table (corresponding to one PDE) contains the mapping for
2 MiB of virtual memory.
Each PTE determines the mapping of a 4 kiB page.

Thus, the linear address is split into three parts.
The most significant bits determine what PDE within the PD to look up, i.e. the
_PD index (PDI)_.
The middle part determines what PTE to look up within the PT, i.e. the _PT
index (PTI)_.
The least significant part is the offset within the page itself.

.32-bit linear address
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

10+| PDI (0-1023) 10+| PTI (0-1023) 12+| Offset (0-4095)
|===

The physical address of the PD is given by CR3.
CR3, PDEs, and PTEs are 32-bit physical addresses pointing to a PD, PT, or page
respectively.
Since all these structures must be aligned with page boundaries, the lower
12 bits of the physical address are always zero and are used for other
purposes.
All of these 12 bits are reserved in CR3 and should be zero.
The upper 20 bits of CR3 are known as the PDBR, or _Page Directory Base
Register_.

.386 page entries
[%header,cols="3,32*"]
|===
| Entry type
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| CR3
20+| PD physical address (31:12)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0

| PDE
20+| PT physical address (31:12)
3+| Available | 0 | 0 | 0 | A | 0 | 0 | U/S | R/W | P

| PTE
20+| Page physical address (31:12)
3+| Available | 0 | 0 | D | A | 0 | 0 | U/S | R/W | P
|===

Physical address:: The physical address of the page (for a PTE), PT (for a
                   PDE), or PD (for CR3).
                   Since pages, PTs, and PDs must be aligned, the lower 12 bits
                   have a different meaning, and are effectively zero when
                   determining the 32-bit physical base address.
                   Alternatively, one can thinkS of the 20-bit field as the
                   index of the page in physical memory.
Available:: These bits are available for use by the operating system.
Dirty bit (D):: PTEs only.
                The CPU automatically sets this bit when the corresponding page
                is written to.
Accessed bit (A):: The CPU automatically sets this bit when the corresponding
                   page, or a page mapped in the corresponding PT, is read or
                   written to.
User/supervisor flag (U/S):: Zero for supervisor; one for user.
                             User pages may be accessed by code at CPL 3.
                             Supervisor pages may only be accessed by Rings 0,
                             1 and 2.
Read/write flag (R/W):: Zero for read-only; one for read-write.
                        Read-only pages may not be written to by code at CPL 3.
Present bit (P):: One indicates the entry may be used.
                  If zero, accessing the corresponding page or PT will cause a
                  page fault, and all the other bits may be used by the
                  operating system.

[NOTE]
Implicit access of data structures through paging, such as the GDT, IDT, LDT or
TSS, are effectively supervisor-mode, even when the current CPL is 3, meaning
that these structures can be protected by paging, while still allowing for e.g.
segment selectors to be loaded and interrupts to be dispatched.

Page protection violations result in a page fault.
Both PTEs and PDEs hold permission bits.
For a page to be a user page, the U/S flag must be set in the corresponding
PTE _and_ PDE.
For a page to be a read-write page, the R/W flag must also be set both in the
PT _and_ in the PD.
This effectively means, the PDE serves as an override to the corresponding
PTEs, that restricts permissions further.

The present bit works in a similar way, in relation to whether the page may be
accessed.
If the PT itself is not present (indicated by a zero in the present bit of the
corresponding PDE), any page mapped by the PT may not be accessed.

[NOTE]
CPUs have a _translation look-aside buffer (TLB)_, that is effectively a cache
of page entries, so the CPU does not have to constantly fetch page entries from
the PD and PT.
This is mostly transparent to the operating system, however the TLB should be
flushed when a page entry is changed that results in some form of more
restricted access compared to the previous state (relaxing access control
does not need a TLB flush, since the processor will load the entry again before
throwing a page fault).
The TLB can be flushed by writing to CR3.

Due to 32-bit addressing, a single segment can now span all of the 4 GiB
linear address space.
This means programs no longer need to be split into multiple segments, instead,
having a single flat segment starting at linear address zero, similar to the
tiny memory model.
Most modern operating systems on the x86 architecture employ this *flat memory
model* and use paging, rather than segmentation, as the primary mechanism for
virtual memory.
This means the GDT only contains a handful of actual segments and the LDT is
completely ignored.

In this scheme, each process has its own isolated linear address space.
This is facilitated by the fact that the TSS has an entry for CR3.
Another advantage of the two-level paging scheme is that common areas of
virtual memories can be mapped in only one set of page tables, that can be then
mapped in the page directory of each individual process, instead of each
process having a its own set of identical page tables for common areas of
virtual memory.

One disadvantage of paging is that it has less fine control over access
permissions.
Pages are aligned 4 kiB blocks, and effectively only have two privilege levels.
Many operating system, however, only use Ring 0 and Ring 3 anyways.
Another problem is that there is no way to restrict execution of pages, while
still allowing it to be read or written.

Modern operating systems implement *software context switching*, rather than
using the hardware context switching facilities.
Modern processors no longer optimize hardware context switching.
In particular, this means there is a fixed amount of task state segments,
meaning, in combination with the flat memory model, that modern operating
systems typically have a fixed amount of entries in the GDT.

==== Page fault ====
The 386 introduces a new exception:

.New 386 exceptions
|===
| Vector | Name | Type | Class | Error code

| 14 | Page fault | Fault | Page fault | Yesfootnote:[Not a segment selector.]
|===

This new exception is special in certain regards:

* Double exception handling is different.
  If a page fault occurs during a contributory exception, the fault and
  exception are handled serially.
  However, if a contributory exception occurs during a page fault, a double
  fault is raised.

* The error code does not provide an entry in a segment descriptor table.
  Instead, it consists of flags indicating the nature of the memory access that
  caused the page fault.
  CR2 stores the linear address that caused the page fault.

.Page fault error code
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| _RMP_ 15+| Reserved
| _SGX_ 8+| Reserved | _SS_ | _PK_ | _I/D_ | _RSV_ | U/S | W/R | P
|===

Present (P):: Zero for a fault caused by a non-present page; one for a
              protection violation.
Write/read flag (W/R):: Zero for a fault caused by a read; one for a fault
                        caused by a write.
User/supervisor flag (U/S):: Zero for a fault caused by a process in user mode;
                             one for a fault caused by a process in supervisor
                             mode.

Following bits are only defined on later processors:

Reserved field set (RSV):: Set if a reserved bit is set (P6 and later only).
                           Faults due to reserved bits being set only occur if
                           PSE or PAE are enabled.
Instruction/date (I/D):: One if the faulting access was an instruction fetch
                         (processors with NX enabled only).
Protection key (PK):: One if a protection key violation was caused (processors
                      with memory protection keys enabled only).
Shadow stack (SS):: One if faulting access was a shadow stack access
                    (processors with control-flow enforcement technology only).
Secure guard extensions (SGX):: One if SGX violation (processors with SGX
                                only).
Reverse map table (RMP):: One if RMP violation (processors with SEV-SNP, an SVM
                          extension, only).

==== Control registers ====
The 386 introduced eight 32-bit control registers CR0 to CR7, that can be
accessed through a regular `mov` instruction to or from a general-purpose
register.

CR0 is a 32-bit extension to the 16-bit MSW that adds two new flags:

Extension type (ET):: Zero for a 287; one for a 387.
                      The 386 automatically initializes this bit.
Paging (PG):: Zero disables paging; one enables paging.
              Must not be set, if PE is zero.

CR1 and CR4 to CR7 are reserved for future use, and cause an undefined opcode
exception.

CR2 stores the linear address of the memory location that triggered a page
fault.

CR3 contains the Page Directory Base Table (PDBR), the physical address of
the page directory.
Since the page directory must be page-aligned, the lower 12 bits are reserved.

==== Debugging ====
Previous x86 CPUs already have certain debugging facilities:

* Interrupt 1, that is invoked on every instruction when the trap flag (TF) is
  set.
  This feature allows for single-stepping.
* Interrupt 3, that can be invoked by the one-byte instruction `int3`, allowing
  for breakpoints.

In addition, the 386 introduces the ability to trap a task through a flag in
the TSS and to invoke interrupt 1 via the one-byte `int1` instruction.

[NOTE]
Intel reserves `int1` for hardware debugging, while software debuggers should
use `int3`.

The 386 also introduces eight debug registers, DR0 to DR7, and corresponding
`mov` instruction.
DR4 and DR5 are reserved, and are aliases to DR6 and DR7 respectively.
DR0 to DR3 contain the linear address of breakpoints zero through three.
DR6 is known as the _Debug Status Register_, and DR7 is known as the _Debug
Control Register_.

DR7 controls under what circumstances the debug exceptions are dispatched:

* R/W0 to R/W3 specify the kind of breakpoint:

  * `00` - Instruction breakpoint.
    Range must be one byte (`00`).
    Causes a fault just _before_ a instruction that starts at the precise
    linear address of the breakpoint is executed.
  * `01` - Causes a trap (i.e. the interrupt is dispatched _after_ the
    instruction is executed) when memory in the range given by DR0 to DR3 and
    LEN0 to LEN3 is written to.
  * `10` - Reserved.
  * `11` - Causes a trap when data is read or written to (see `01`).

* The LEN0 to LEN3 fields control the range of bytes that are affected by a
  data breakpoint.
  The linear address must be aligned according to the range field (i.e. 2 byte
  breakpoints must be word-aligned, 4 byte breakpoints must be dword-aligned).

  * `00` - 1 byte
  * `01` - 2 byte
  * `10` - 8 byte (AMD long mode and certain Intel processors only; reserved
    otherwise)
  * `11` - 4 byte

* G0 to G3 enable the respective breakpoint globally.

* L0 to L3 enable the respective breakpoint locally.
  This means they are reset automatically on a task switch.

* GE and LE slow the processor down, so that data breakpoints happen on the
  correct instruction.
  LE is automatically cleared on a task switch.

DR6 indicates the cause of a debug exception.
The fields are set automatically by the processor, but never reset.

* B0 to B3 indicate a fault or trap due to a breakpoint.
* BT indicates a trap due to the T flag in a TSS.
* BS indicates a single-step trap due to the trap flag TF.
* BD indicates a "general detect fault" caused by reading or writing a debug
  register.
  This happens, when an in-circuit emulator (such as the ICE-386) is using the
  debug registers.

Since instruction breakpoints are a fault, resuming the fault may cause the
breakpoint to happen again.
To deal with this, the _resume (or restart) flag (RF)_ was introduced.
This flag is automatically set on the saved EFLAGS register, whenever any fault
occurs.
If RF is set, instruction breakpoints are disabled for one instruction, since
the flag is automatically cleared once an instruction finishes successfully.

==== Test registers
In addition to control and debug registers, the 386 has a `mov` instruction for
eight test registers.
However, only TR6, the _test command register_, and TR7, the _test control
register_, exist.
These serve to test the TLB during early initialization.

==== Virtual 8086 mode
In order to allow real mode programs to run under protected mode, the 386
introduces *virtual 8086 mode (VM86 mode)*.
The processor is in VM86 mode if the _VM flag_ in the EFLAGS register is set.

The VM flag can only be toggled through an `iret` in Ring 0 or a task switch,
in order to update the segment registers, the instruction pointer, and stack
pointer to a valid state (trying to change the VM flag through `popf` will not
result in a change of VM).
A task in VM86 mode is referred to as a _VM86 task_.
It runs under the supervision of a protected mode program called the _VM86
monitor_.

In VM86 mode, segmentation works in a similar way to real mode: the segment
base linear address is 16 times the segment selector value, and the limit is
always 65535.
The CPL in VM86 mode is always 3.

Paging, however, works as it does in protected mode.
In particular, the VM86 task can access the first mebibyte (plus 64 kiB minus
16 bytes) of linear address space, meaning that, if paging is enabled, this
memory does not have to be mapped to the first megabyte of memory, allowing
for multiple VM86 tasks.
Paging protection also applies, which allows the VM86 monitor to catch access
to certain memory areas.

The instructions that are sensitive to IOPL change in VM86 mode.
In particular, the I/O instructions `in`, `out`, `ins`, and `outs` are no
longer sensitive to IOPL, and `pushf`, `popf`, `iret`, and `int` (but not
`int3`, `into`, and `int1`) are now sensitive to IOPL.
`cli`, `sti`, and `lock` remain sensitive.
This means, if the IOPL is 3, the VM86 tasks may directly control the interrupt
flag, and may issue software interrupts directly, otherwise a general
protection fault is dispatched.

VM86 mode handles interrupts in a similar way to native protected mode.
The IDT is used, rather than the real mode IVT.
The corresponding IVT entry for an interrupt in VM86 mode must point to a
interrupt or trap gate pointing to a nonconforming code segment with
DPL 0, or a task gate.
If the resulting CPL of a interrupt or trap gate is not zero, a general
protection fault occurs.

When an interrupt causes a switch out of VM86 mode through an interrupt or trap
gate, in addition to updating CS:EIP (to the target of the gate) and SS:ESP
(with the SS0:ESP0 field of the current TSS), the other segment registers DS,
ES, FS, and GS are also pushed on the stack and set to null selectors, since
they contained real mode segment addresses, and not necessarily valid protected
mode segment selectors.

I/O permissions work much like protected mode, except that IOPL is ignored.
Instead, the I/O permission bitmap is always consulted, meaning the IOPL is
effectively zero.

.32-bit call stack (ESP = -4 if error code, ESP = 0 otherwise)
[%collapsible]
====
[%header,cols="7*"]
|===
| 2+| Call 2+| Interrupt
2+| Interrupt +
    from VM86 mode

| Address | +2 | +0 | +2 | +0 | +2 | +0

| 36 2.5+| 2.4+| 2+| = SS0:ESP0

| 32 | | FS

| 28 | | GS

| 24 | | DS

| 20 2+| (= SSn:ESPn) | | ES

| 16 2+| (= SSn:ESPn) | | (SS) | | SS

| 12 | | (SS) 2+| (ESP) 2+| ESP

| 8 2+| (ESP) 2+| EFLAGS 2+| EFLAGS

| 4 | | CS | | CS | | CS

| 0 2+| EIP 2+| EIP 2+| EIP

| -4 2+| 2+| (Error code) 2+| (Error code)
|===
====

=== i486
The 486 expanded the 386 by introducing an integrated FPU and L1 cache.
486-class processors include the Cx486 and Am486, as well as the Am5x86 (but
not the Cx5x86).
It also introduced the `cmpxchg` and `xadd` instructions, that are useful for
synchronization, and `bswap` to convert between big and little endian.
New mechanisms that allow finer control of caching were also introduced.

.486 registers
[%collapsible]
====
[%header,cols="3,32*"]
|===
| Register
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| EAX 16+| (EAX) 8+| AH (AX) 8+| AL (AX)

| ECX 16+| (ECX) 8+| CH (CX) 8+| CL (CX)

| EDX 16+| (EDX) 8+| DH (DX) 8+| DL (DX)

| EBX 16+| (EBX) 8+| BH (BX) 8+| BL (BX)

| ESP 16+| (ESP) 16+| SP

| EBP 16+| (EBP) 16+| BP

| ESI 16+| (ESI) 16+| SI

| EDI 16+| (EDI) 16+| DI

| EIP 16+| (EIP) 16+| IP

| EFLAGS
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | *AC* | VM | RF
| 0 | NT 2+| IOPL | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| CR0
| PG | *CD* | *NW* | | | | | | | | | | | *AM* | | *WP*
| | | | | | | | | | | *NE* | ET | TS | EM | MP | PE

| CR2 32+| Page fault linear address

| CR3 20+| Page Directory Base Register (PDBR)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | *PCD* | *PWT* | 0 | 0 | 0

| DR0 32+| Breakpoint 0 linear address

| DR1 32+| Breakpoint 1 linear address

| DR2 32+| Breakpoint 2 linear address

| DR3 32+| Breakpoint 3 linear address

| DR6
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
| BT | BS | BD | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | B3 | B2 | B1 | B0

| DR7
2+| LEN3 2+| R/W3 2+| LEN2 2+| R/W2 2+| LEN1 2+| R/W1 2+| LEN0 2+| R/W0
| 0 | 0 | 0 | 0 | 0 | 0 | GE | LE | G3 | L3 | G2 | L2 | G1 | L1 | G0 | L0

| ESfootnote:[Hidden descriptor caches are omitted.]
16+| 16+| ES (visible selector)

| CS 16+| 14+| (visible CS selector) 2+| CPL

| SS 16+| 14+| (visible SS selector) 2+| CPL

| DS 16+| 16+| DS (visible selector)

| FS 16+| 16+| FS (visible selector)

| GS 16+| 16+| GS (visible selector)

| TR 16+| 16+| TR (visible selector)

| LDTR 16+| 16+| LDTR (visible selector)

.2+| GDTR 32+| Base 16+| 16+| Limit

.2+| IDR 32+| Base 16+| 16+| Limit
|===
====

Since the FPU is now integrated, numeric exceptions can be routed internally to
interrupt 16.
However, to maintain compatibility with older implementations where the FPU is
external and the exception can be routed through another interrupt, the 486 has
the option to route the exception externally over the motherboard.
The _numeric error (NE)_ bit in CR0 has to be set to enable the native
mechanism.

The 486 also introduces a feature to enforce aligned data access.
The alignment check happens when the _alignment check (AC)_ flag in EFLAGS
_and_ the _alignment mask (AM)_ bit in CR0 are set _and_ if the processor is in
Ring 3.
When a alignment violation happens, the an alignment check fault is raised.

.New 486 exceptions
|===
| Vector | Name | Type | Class | Error code

| 17 | Alignment check | Fault | Benign | Yesfootnote:[Always zero.]
|===

==== Cache control
The new `invd` and `wbinvd` instruction invalidate the cache.
While the `invd` instruction may cause data loss on a writethrough cache, due
to not writing back changes, the `wbinvd` updates the memory with changes,
before invalidating the cache.

The `invlpg` instruction lets the operating system invalidate an individual TLB
entry, rather than invalidating all of them through writing to CR3.

The 486 also expanded the test registers of the 386.
In addition to TR6 and TR7, the 486 introduced TR3 (the _cache test data
register_), TR4 (the _cache test status register_) and TR5 (the _cache test
control register_), to test the internal writethrough L1 cache.

Two new flags were added to CR0 for global cache control:

* _Cache disable (CD)_ disables the allocation of new cache lines, meaning read
  cache misses are read directly from main memory, but no cache line gets
  replaced.
  To completely disable the cache, the CD bit is set and the cache is flushed
  through `wbinvd`.
  On CPUs with MTRR (see MTRR section), the memory type may need to be set to
  uncacheable (UC) when setting the CD, in order to preserve strong memory
  ordering (which can be done by disabling MTRRs).

* _No writethrough (NW)_ may only be set if CD is also set and causes cache
  coherence to no longer be maintained, i.e. write cache misses are written to
  the cache and never written back to main memory.
  On P6 processors and later, setting the NW bit disables writeback caching,
  forcing pages to writethrough, regardless of PWT (see below) and MTTRs
  (see MTRR section).

Having NW one and CD zero is invalid and causes a general protection fault.

[NOTE]
====
The effect of the CD and NW bits varies over implementations:

* The NW bit does not exist on Cx486 processors.

* The NW bit has a different meaning on Cx5x86, 6x86, MII, and MediaGX
  processors.

* The NW bit is ignored on Intel Pentium 4 and later, as well as any AMD64
  implementation.

* The CD bit disables caching completely on Intel Atom CPUs.

* If the CD bit is set, 64-bit AMD processors automatically invalidate (and
  write back) a cache line on a cache hit.
====

==== Paging
If the new _write protect (WP)_ bit in CR0 is set, writing to a read-only page
will cause a page fault, even in supervisor mode.

.486 page entries
[%header,cols="3,32*"]
|===
| Entry type
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| CR3
20+| PD physical address (31:12)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | *PCD* | *PWT* | 0 | 0 | 0

| PDE
20+| PT physical address (31:12)
3+| Available | 0 | 0 | 0 | A | *PCD* | *PWT* | U/S | R/W | P

| PTE
20+| Page physical address (31:12)
3+| Available | 0 | 0 | D | A | *PCD* | *PWT* | U/S | R/W | P
|===

Page-level cache disable (PCD):: Disables caching for this page.
                                 This bit (as well as the PWT bit) is present
                                 in CR3, PDEs, and PTEs.
                                 CR3 controls caching for the PD, the PDE
                                 controls caching for the PT, and the PTE
                                 controls caching for the page.
Page-level writethrough (PWT):: Disables any writeback cache for this page
                                (in particular external ones, the 486 has an
                                internal writethrough cache).
                                See PCD.

=== i586
586-class processors include the Intel Pentium and Pentium MMX, the AMD K5, the
NexGen Nx586, as well as the Cyrix Cx5x86, Cx6x86 and MediaGX.
In addition to adding the `cmpxchg8b` and `cpuid` instructions, the Pentium
introduced MSRs, machine checks, and the TSC, along with extensions to paging,
virtual 8086 mode, and debugging.
The Pentium introduces CR4 to control processor extensions.

.IA-32 registers
[%collapsible]
====
[%header,cols="3,32*"]
|===
| Register
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| EAX 16+| (EAX) 8+| AH (AX) 8+| AL (AX)

| ECX 16+| (ECX) 8+| CH (CX) 8+| CL (CX)

| EDX 16+| (EDX) 8+| DH (DX) 8+| DL (DX)

| EBX 16+| (EBX) 8+| BH (BX) 8+| BL (BX)

| ESP 16+| (ESP) 16+| SP

| EBP 16+| (EBP) 16+| BP

| ESI 16+| (ESI) 16+| SI

| EDI 16+| (EDI) 16+| DI

| EIP 16+| (EIP) 16+| IP

| EFLAGS
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | *ID* | *VIP* | *VIF* | AC | VM | RF
| 0 | NT 2+| IOPL | OF | DF | IF | TF | SF | ZF | 0 | AF | 0 | PF | 1 | CF

| CR0
| PG | CD | NW | | | | | | | | | | | AM | | WP
| | | | | | | | | | | NE | ET | TS | EM | MP | PE

| CR2 32+| Page fault linear address

| CR3 20+| Page Directory Base Register (PDBR)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | PCD | PWT | 0 | 0 | 0

| CR4
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
| 0 | 0 | 0 | 0 | 0 | _OS +
  XMM +
  EX +
  CPT_ | _OS +
  FX +
  SR_
| _PCE_ | _PGE_ | *MCE* | _PAE_ | *PSE* | *DE* | *TSD* | *PVI* | *VME*

| DR0 32+| Breakpoint 0 linear address

| DR1 32+| Breakpoint 1 linear address

| DR2 32+| Breakpoint 2 linear address

| DR3 32+| Breakpoint 3 linear address

| DR6
| 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | _RTM_
| BT | BS | BD | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | B3 | B2 | B1 | B0

| DR7
2+| LEN3 2+| R/W3 2+| LEN2 2+| R/W2 2+| LEN1 2+| R/W1 2+| LEN0 2+| R/W0
| 0 | 0 | *GD* | 0 | _RTM_ | 1 | GE | LE | G3 | L3 | G2 | L2 | G1 | L1 | G0 | L0

| ESfootnote:[Hidden descriptor caches are omitted.]
16+| 16+| ES (visible selector)

| CS 16+| 14+| (visible CS selector) 2+| CPL

| SS 16+| 14+| (visible SS selector) 2+| CPL

| DS 16+| 16+| DS (visible selector)

| FS 16+| 16+| FS (visible selector)

| GS 16+| 16+| GS (visible selector)

| TR 16+| 16+| TR (visible selector)

| LDTR 16+| 16+| LDTR (visible selector)

.2+| GDTR 32+| Base 16+| 16+| Limit

.2+| IDR 32+| Base 16+| 16+| Limit
|===
====

Virtual interrupt flag (VIF):: See VME.
Virtual interrupt pending (VIP):: See VME.
ID flag:: The ability to toggle this flag indicates the presence of `cpuid`.
Virtual 8086 mode extensions (VME):: VME is enabled if set.
Protected-mode virtual interrupts (PVI):: PVI is enabled if set.
Timestamp disable (TSD):: When set, prevents execution of `rdtsc` when the CPL
                          is not zero (see TSC section).
Debugging extensions (DE):: When set, DR4 and DR5 are no longer aliases to DR6
                            and DR7, and instead cause invalid opcode
                            exceptions, much like CR1.
Page size extensions (PSE):: PSE for 32-bit paging is enabled if set.
Machine-check enable (MCE):: Machine-check exception is enabled when set.
Performance monitoring counter enable (PCE):: Allows `rdpmc` in privilege rings
                                              other than Ring 0 (Pentium MMX,
                                              P6 and later, see MSR section).
General detect (GD):: Setting this bit causes a debug fault whenever the debug
                      registers are accessed (general detect exception).
                      Intended for preventing software interfering with
                      emulators.
                      The GD bit is automatically cleared on a debug exception.

Following flags are only implemented in later processor families:

Physical address extension (PAE):: PAE is enabled if set (P6 and later).
Page global enable (PGE):: PGE is enabled if set (P6 and later).
OS support for `fxsave` and `fxrstor` (OSFXSR):: `fxsave` and `fxrstor` will
                                                 save and restore SSE registers
                                                 when set.
                                                 In addition, it enables the
                                                 execution of SSE instructions
                                                 (Pentium III and later).
OS support for SSE exceptions (OSXMMEXCPT):: The CPU will cause a undefined
                                             opcode exception (interrupt 6)
                                             when an SSE floating-point error
                                             occurs if cleared. 
                                             When set, a SIMD floating-point
                                             exceptions occurs
                                             (Pentium III and later).
Restricted transactional memory (RTM):: Processors with TSX only.

==== CPUID
Pentium and late 486 models support the `cpuid` instruction, in order to
facilitate the detection of CPU models.
The ability to toggle the _ID flag_ in EFLAGS indicates the presence of the
`cpuid` instruction.

`cpuid` returns a variety of information in EAX, EBX, ECX and EDX,
based on the initial value of EAX, the _function number_.
There are standard function numbers, starting from 0x00000000, and extended
function numbers, starting from 0x80000000.

Important functions include:footnote:[The original Pentium and late 486 only
has the first two standard functions; further functions were added successively
in later generations.]

* EAX = 0x00000000 returns the highest standard function number in EAX and
  a 12 byte vendor string in EBX, ECX, and EDX.
  The vendor string is "GenuineIntel" for Intel processors, and "AuthenticAMD"
  for AMD processors.
* EAX = 0x80000000 returns the highest extended function number in EAX.
* EAX = 0x00000001 returns version information in EAX and feature bits in EDX
  and ECX.
* EAX = 0x80000001 returns provides more feature bits in EDX and ECX.
* EAX = 0x00000007 provides subfunctions based on the value of ECX:
  * ECX = 0 returns the highest subfunction number in EAX.
    EBX, ECX and EDX contain even more feature bits.
  * ECX = 1 returns a further set of feature bits in EAX and EBX.
* EAX = 0x80000002, 0x80000003, 0x80000004 return part of the processor brand
  string in EAX, EBX, ECX, and EDX.
  The entire string is therefore 48 bytes long.
* EAX = 8x00000008 returns the physical address width in AL and the linear
  address width in AH.

There exist many other functions that might be relevant to operating system
development, such as information on multiprocessor topology.
The feature bits are used to indicate the presence of a certain processor
extension.
They are generally set if the processor extension is present, and cleared if it
is not preset (see the extensions section for more detailed information).

The version information consists of a family, model, and stepping ID.
If the family ID field is 15, then the extended family ID field is added to the
family field to obtain the actual processor family number.
If the family ID field is 6footnote:[Not on AMD.] or 15, the model number is
the extended model ID times 16 plus the model ID.

The processor type is 0 for a regular processor, 1 for a Pentium OverDrive and
2 for a second processor.

.CPUID version information
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

4+| 8+| Extended family 4+| Extended model
2+| 2+| Typefootnote:[Intel only.] 4+| Family 4+| Model 4+| Stepping
|===

It is recommended to check for extensions using the feature bits when possible,
rather than based on family and model.

=== i686
The term 686 is somewhat ambiguous, and often refers to one of following
things:

* Sixth-generation x86 processors (Intel Pentium Pro, Pentium II, and Pentium
  III, and AMD K6, K6-2, and K6-III), which were released around the same time
  as, and competed directly with the Intel Pentium Pro, II, and III.
* Processors supporting the Pentium Pro instruction set.
  This excludes the AMD K6, K6-2, and K6-III, but includes the AMD Athlon (K7)
  and later.
  This may include all later processors as well, or exclude processors
  supporting SSE2, i.e. NetBurst (i.e. Pentium 4), x86-64 (i.e Athlon 64), and
  later, or exclude processors supporting x86-64.
* Family 6 processors, which correspond to all Intel processors after the
  Pentium Pro, except for NetBurst-based ones (but including later Core-branded
  processors), and the AMD K7.

=== i786
The term 786 may refer to either x86-64 processors or a category between 686
and x86-64:

* Processors with SSE2, which would include the NetBurst-based Pentium 4.
* Seventh-generation microarchitectures, which would include NetBurst and K7.

=== x86-64

== Extensions
New features that were introduced after the 486 are usually processor
extensions, whose presence can be directly and separately determined via
`cpuid`.
There are exceptions, however, such as `ud2`, long `nop`, and `rdpmc` (along
with the corresponding PCE flag), whose presence are not indicated by any
feature bit.

.New exceptions
|===
| Vector | Name | Type | Class | Error code | Extension

| 18 | Machine-check exception | Abort | Benign | No | MCE

| 19 | SIMD floating-point exception | Fault | Benign | No | SSE

| 20 | Virtualization exception | Fault | Benign | No | EPT (VMX)

| 21 | Control protection exception | Fault | Benign
| Yesfootnote:[Not a segment selector.] | CET

| 28 | Hypervisor injection exception | | Benign | No | SEV-SNP (SVM)

| 29 | VMM communication exception | Fault | Contributory | No | SEV-ES (SVM)

| 30 | Security exception | | Contributory | No | SVM
|===

Following tables contain a list of x86 extensions supported by Intel and AMD.
There exist other extensions indicated by feature bits obtained through other
`cpuid` functions or MSRs.
These are mostly manufacturer-specific, however, and are usually extensions to
other extensions, or power management features.

.EAX = 0x00000001
[%header,cols=7]
|===
| Bit 2+| Acronym and name | First specified
| First implemented (Intel) | First implemented (AMD) | Level

| EDX.0 | FPU | Integrated x87 floating-point unit
| | i486DX (1989) | Am486DX (1993) | i387

| EDX.1 | VME | Virtual 8086 mode enhancements
| | P5 (Pentium, 1993) | K5 (5k86, 1996) |

| EDX.2 | DE | Debugging extensions
| | P5 (Pentium, 1993) | K5 (5k86, 1996) |

| EDX.3 | PSE | Page size extensions
| | P5 (Pentium, 1993) | K5 (5k86, 1996) |

| EDX.4 | TSC | Time stamp counter
| | P5 (Pentium, 1993) | K5 (5k86, 1996) | i586

| EDX.5 | MSR | Model-specific registers
| | P5 (Pentium, 1993) | K5 (5k86, 1996) | i586

| EDX.6 | PAE | Physical address extension
| | P6 (Pentium Pro, 1995) | K7 (Athlon, 1999) |

| EDX.7 | MCE | Machine-check exception
| | P5 (Pentium, 1993) | K5 (5k86, 1996)footnote:[AMD processors before the K7
never raise the machine-check exception.] |

| EDX.8 | CX8 | `cmpxchg8b`
| | P5 (Pentium, 1993) | K5 (5k86, 1996) | i586

| EDX.9 | APIC | Integrated local APIC
| | P54C (Pentium, 1994) | K75 (Athlon, 1999)footnote:[Early K5s use this bit
to indicate the presence of PSE, rather than a LAPIC.] |

| EDX.11 | SEP | `sysenter` and `sysexit`
| | Klamath (Pentium II, 1997)footnote:[The Pentium Pro has this bit set, but
does not implement the feature correctly.] | K7 (Athlon, 1999) | i686

| EDX.12 | MTRR | Memory type range registers
| | P6 (Pentium Pro, 1995) | K7 (Athlon, 1999) |

| EDX.13 | PGE | Global paging extensions
| | P6 (Pentium Pro, 1995) | K5 (5k86, 1996)footnote:[Early K5s use bit 9 to
indicate the presence of PSE, rather than a LAPIC.] |

| EDX.14 | MCA | Machine-check architecture
| | P6 (Pentium Pro, 1995) | K7 (Athlon, 1999) |

| EDX.15 | CMOV | `cmov` instruction
| | P6 (Pentium Pro, 1995) | K7 (Athlon, 1999) | i686

| EDX.16 | PAT | Page attribute table
| | Katmai (Pentium III, 1999) | K7 (Athlon, 1999) |

| EDX.17 | PSE-36 | 36-bit page size extensions
| | Deschutes (Pentium II Xeon, 1998) | K75 (Athlon, 1999) |

| EDX.18 | PSN | Processor serial number
| | Katmai (Pentium III, 1999)footnote:[Pentium III only. Removed with
Tualatin.] | Never |

| EDX.19 | CFLSH | `cflush` instruction
| | Katmai (Pentium III, 1999) | SledgeHammer (K8, Opteron, 2003) | SSE

| EDX.21 | DS | Debug store (for profiling, used by BTS and PEBS)
| | Willamette (NetBurst, Pentium 4, 2000) | Never |

// note (lukflug): reference for this in Intel SDM page 3336
| EDX.22 | ACPI | Support for thermal monitoring and clock modulation MSRs (not
ACPI)
| | Willamette (NetBurst, Pentium 4, 2000) | Never |

| EDX.23 | MMX | Multimedia extensions
| | P55C (Pentium MMX, 1996) | K6 (1997) | MMX

| EDX.24 | FXSR | Support for `fxsave` and `fxrstor`
| | Katmai (Pentium III, 1999) | K75 (Athlon, 1999) | SSE

| EDX.25 | SSE | Streaming SIMD extensions
| | Katmai (Pentium III, 1999) | Palomino (Athlon XP, 2001) | SSE

| EDX.26 | SSE2 | SSE2
| | Willamette (NetBurst, Pentium 4, 2000) | SledgeHammer (K8, Opteron, 2003)
| SSE2 or i786

// note (lukflug): reference: https://www.cpu-world.com/CPUs/Pentium_4/Intel-Pentium%204%201.6%20GHz%20-%20RK80532PC025512%20(BX80532PC1600D).html
| EDX.27 | SS | Self snoop
| | Northwood (Pentium 4, 2002) | Never |

| EDX.28 | HTT | Hyper-threading technology
| | Foster MP (Xeon, 2002) | Bulldozer (AMD FX, 2011) |
|===

=== Model-specific registers
The Pentium and subsequent processors no longer have the test registers of the
386 and 486.
Instead, it introduces *model-specific registers (MSRs)*.
MSRs are 64-bit registers that are addressed using a 32-bit number and are
accessed via the Ring 0-only `rdmsr` and `wrmsr` instructions.

The first two MSRs are related to the *machine-check architecture*.
The machine-checks are model-specific exceptions that usually indicate critical
errors.
Information on a machine-check exception is available in relevant MSRs,
although the details have changed with P6-based processors and later.
Machine-checks are enabled when the _machine-check enable (MCE)_ bit of CR4 is
set.

The Pentium also introduces the _time stamp counter (TSC)_ MSR, that can be
read in user mode through the `rdtsc` instruction.
Setting the _time stamp disable (TSD)_ bit of CR4 restricts `rdtsc` to Ring 0.

The later Pentium MMX variant, in addition to introducing MMX, includes the
`rdpmc` instruction from the Pentium Pro to read so-called
_performance-monitoring counters (PMCs)_ MSRs.
This instruction can be executed in user mode, by setting the
_performance-monitoring counter enable (PCE)_ bit of CR4.

=== Page size extensions
The *Page Size Extensions (PSE)* are enabled through the PSE bit of CR4.
PSE introduces a new bit in PDEs, that allows for 4 MiB pages, rather
than a PT with 1024 4 kiB pages.

.PSE page entries
[%header,cols="3,32*"]
|===
| Entry type
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| CR3
20+| PD physical address (31:12)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | PCD | PWT | 0 | 0 | 0

| PDE
20+| PT physical address (31:12)
3+| Available | 0 | *PS* | 0 | A | PCD | PWT | U/S | R/W | P

| PDE
10+| 4 MiB page physical address (31:22)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
3+| Available | 0 | *PS* | D | A | PCD | PWT | U/S | R/W | P

| PTE
20+| 4 kiB page physical address (31:12)
3+| Available | 0 | 0 | D | A | PCD | PWT | U/S | R/W | P
|===

Page size (PS):: PD only.
                 Zero for 4 kiB pages; one for 4 MiB pages.
Dirty bit (D):: Exists in PDEs for 4 MiB pages.

4 MiB pages must be 4 MiB aligned, therefore bits 12 to 21 are reserved.

=== Virtual 8086 mode extensions
*Virtual Mode Extensions (VME)* allow for interrupt handling inside virtual
8086 mode, without switching to protected mode, thereby increasing performance.
It is enabled by setting the VME bit in CR4.

With VME enabled, software interrupts caused by the `int` instruction (but not
`int3`, `into` and `int1`) may be handled by handlers in virtual 8086 mode,
using the real-mode IVT at linear address zero.
A 32-byte bitmap (one bit for every interrupt vector), that is located just
below the I/O permission bitmap (i.e. the base of the interrupt redirection
bitmap is the I/O map base minus 32) in the TSS is, is used to determine how a
software interrupt is dispatched.

If the bit corresponding to the interrupt vector is set, the interrupt is
handled in protected mode using the IDT (or causes a general protection fault,
if the IOPL is not 3).
If the bit is cleared, the interrupt is handled in virtual 8086 mode, as if it
is a real mode interrupt (the IOPL field of the pushed FLAGS register is always
set to 3).
Hardware interrupts and exceptions, however, are always handled through
protected mode interrupt handlers.

VME also introduces the _virtual interrupt flag (VIF)_ and the _virtual
interrupt pending (VIP)_ flag, for the VM86 task to be able to prevent
asynchronous hardware interrupts affecting its state, without disabling
hardware interrupts for all tasks or causing a fault (meaning a costly switch
to protected mode).
When VME is enabled and the IOPL is less than 3, `cli`, `sti`, `popf` and
`iret` will not update the interrupt flag IF (nor cause a general protection
fault), rather it will update VIF.
`pushf` and a `int` to a virtual 8086 mode handler (i.e. with the corresponding
bit in the bitmap cleared) will store VIF, rather than IF, when pushing the
FLAGS register.

Having VIF and VIP set simultaneously in VM86 mode (such as running `sti`
virtual 8086 mode while VIP is set) will cause a general protection fault.
This means when a hardware interrupt occurs, the protected mode handler can
check the VIF flag.
If it is cleared, the VM86 task does not expect hardware interrupts, and the
VM86 monitor can set the VIP flag and return to the VM86 task.
When the VM86 task sets the IF flag, it will transparently set the VIF flag
instead, and cause a general protection fault, due to the VIP flag also being
set.
The VM86 monitor can then handle the hardware interrupt belatedly and clear the
VIP flag and set the VIF flag and return.

The _protected mode virtual interrupts (PVI)_ bit of CR4 enables the VIF and
VIP mechanism for protected mode.
If the PVI bit is set, the CPL is 3 and the IOPL is less than 3, the `cli` and
`sti` instructions (`pushf`, `popf`, `int` and `iret` are not affected) will
change the VIF flag, rather than the IF flag.
As in VM86, having VIF and VIP set simultaneously causes a general protection
fault.
Therefore, the handling of maskable hardware interrupts and also be delayed, as
with VM86 mode, at the request of user mode software.

[NOTE]
VIF and VIP, like VM, cannot be directly changed through `popf` and can only be
changed through a `iret` in Ring 0 or a `popf` in Ring 1.
VIF can be indirectly changed in Ring 3 by attempting to change IF, if VME is
set in VM86 mode or if PVI is set in native protected mode.

=== Debugging extensions
The functionality of the debug registers was extended in the Pentium in three
ways:

* The R/W0 to R/W3 fields now allow for the `10` value, which was previously
  reserved.
  The `10` value sets an I/O breakpoint (same alignment requirements as data
  break point).
* The _debug extensions (DE)_ bit of CR4, which disables the aliasing of DR4
  and DR5 to DR6 and DR7 when set.
  If this bit is set, reading or writing to DR4 and DR5 cause an invalid opcode
  exception, similar to CR1.

=== PGE
Setting the *page global enable (PGE)* bit in CR4 enables the a new bit in page
entries, that allows operating systems to mark regions of linear address space
that are common to all processes (and therefore global).
The CPU will not flush global pages when swapping address space (i.e. updating
CR3), increasing TLB efficiency.

.PGE page entries (with PSE)
[%header,cols="3,32*"]
|===
| Entry type
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

| CR3
20+| PD physical address (31:12)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | PCD | PWT | 0 | 0 | 0

| PDE
20+| PT physical address (31:12)
3+| Available | 0 | PS | 0 | A | PCD | PWT | U/S | R/W | P

| PDE
10+| 4 MiB page physical address (31:22)
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
3+| Available | *G* | PS | D | A | PCD | PWT | U/S | R/W | P

| PTE
20+| 4 kiB page physical address (31:12)
3+| Available | *G* | 0 | D | A | PCD | PWT | U/S | R/W | P
|===

Global (G):: If set, the CPU will not flush this page from the TLB when
             updating CR3.

=== PAE
The Pentium Pro extended the physical address space to 36-bit.
This allows for up to 64 GiB of RAM.
In order to access this new memory, a new paging mechanism is introduced,
*Physical Address Extension (PAE)*, which allows pages to be mapped above 4
GiB.
PAE is transparent to application programs and the linear address space is
still restricted to 4 GiB.

PAE is enabled by the PAE bit in CR4 and modifies paging by increasing the size
of page entries to 64-bit, meaning that a page table now can only hold 512 page
entries, rather than 1024.
This means a third level is introduced, the *page directory pointer table
(PDPT)*.
This table contains four _page directory pointer table entries (PDPTEs)_ to
four PDs, each covering 1 GiB of linear address space and containing 512
entries to PDs, each covering 2 MiB of linear address space and containing 512
entries to 4 kiB pages.

The upper part of the linear address is known as the _page directory pointer
table index (PDPTI)_.

.PAE linear address
[%header,cols="32*"]
|===
| 31 | 30 | 29 | 28 | 27 | 26 | 25 | 24 | 23 | 22 | 21 | 20 | 19 | 18 | 17 | 16
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0

2+| PDPTI 9+| PDI (0-511) 9+| PTI (0-511) 12+| Offset (0-4095)
|===

PAE allows for large pages, that are 2 MiB in size, rather than 4 MiB,
regardless of the state of the PSE bit.

== Floating-point and vector extensions
x86 processors have a plethora of extensions, that expand on the
general-purpose instruction set.

=== x87
*x87*, also known as _Numerical Processing Extension (NPX)_ or _FPU_, is a
scalar floating-point calculation extension.
Units that implement x87 are often referred to as "the FPU", although the term
may also apply to the SIMD floating-point extensions listed below.
Originally implemented as a separate coprocessor, it is integrated into the
486DX and most processors that came after it.

The instruction set primarily operates on a stack of eight 80-bit registers
that are addressed as ST(0) to ST(7) relative to the top of the stack.

=== MMX
*Multimedia Extensions (MMX)*, introduced in 1997 with the Pentium MMX, is a
SIMD (single instruction; multiple data) extension.
AMD first implemented MMX in the K6 in 1997.
MMX only supported integer math and operated on aliases to the 64-bit
significand part of the x87 registers, called MM0 to MM7.
Unlike x87, MMX addresses those registers directly, without a stack pointer.
This aliasing makes it difficult for applications to use MMX and x87 at the
same time.

==== 3DNow!
In 1998, AMD introduced *3DNow!* with the K6-2.
This extended MMX to introduce support for operations on 32-bit floating-point
data.
AMD introduced an extended version of 3DNow! in 1999 with the original Athlon.
This also includes a subset of new MMX integer instructions introduced with
SEE.
Starting with AMD Bulldozer CPUs, 3DNow! is no longer supported (except for two
instructions that are also found in newer Intel processors).

=== SSE
*Streaming SIMD Extensions (SSE)*, also known as _Katmai New Instructions
(KNI)_ or _Internet Streaming SIMD Extensions (ISSE)_, is a SIMD extension,
introduced in 1999 with the Intel Pentium III, and supported by AMD since the
Athlon XP in 2001.
In addition to adding new instructions to the existing MMX integer instruction
set, it introduces a new set of eight 128-bit registers, XMM0 to XMM7, that can
each store four 32-bit floating-point numbers.

==== SSE2
*SSE2*, also known as _Willamette New Instructions (WNI)_, was introduced in
2000 with the Intel Pentium 4.
AMD first implemented it with the x86-64 Opteron in 2003.
SSE2 adds support for 64-bit floating-point numbers and integers of sizes
ranging from 8-bit to 64-bit, through MMX-like instructions on SSE registers.
Thus, it is a full replacement of MMX and a partial replacement for x87 (though
x87 supports higher precision 80-bit floating-point math).

AMD's x86-64 implementation introduced eight new registers, XMM8 to XMM15,
that can only be used in 64-bit mode.
In fact, SSE2 with 16 registers is mandatory for every x86-64 implementation.

==== SSE3
*SSE3*, also known as _Prescott New Instructions (PNI)_, was introduced by
Intel in 2004 with the Prescott Pentium 4, and by AMD in 2005 with the Athlon
XP Revision E.
This extension introduces support for "horizontal" operations between values in
the same register.

==== SSSE3
*Supplementary Streaming SMD Extenions 3 (SSSE3)*, also known as _Merom New
Instructions (MNI)_, was first implemented by Intel in 2006 with Woodcrest
Xeons, and by AMD with Bulldozer AMD FX CPUs in 2011.
It is not to be confused with SSE4.

==== SSE4
*SSE4* is divided into two subsets by Intel.
The first subset, *SSE4.1*, also known as _Penryn New Instructions (PNI)_, was
introduced with Penryn Core 2 CPUs in 2007.
The second subset, *SSE4.2*, also known as _String and Text New Instructions
(STTNI)_, was introduced with Nehalem Core i7 CPUs in 2008.
Nehalem also introduces performance improvements for misaligned data.
While SSE4.1 adds new SIMD instructions, such as a dot product instruction,
SSE4.2 adds string search and comparison instructions, and a CRC32 instruction.

AMD introduced its own subset of SSE4, *SSE4A*, with the K10 in 2007.
SSE4A introduces four instructions not available on any Intel processor.
AMD started supporting the full SSE4 instruction set with the Bulldozer
architecture in 2011.
With SSE4A, AMD also introduced greater support for operations with misaligned
data, which is supported by Intel since AVX.

==== SSE5
*SSE5* is a proposed extension by AMD in 2007.
It does not include all SSE4 instructions, and proposes a new _DREX encoding_,
which is incompatible with AVX's VEX encoding.
This extension was never implemented in hardware. having to be revised and
split into F16C, XOP and FMA4 in 2009, in order to remain compatible with AVX.

==== F16C
*F16C*, also known as *CVT16*, originally proposed by AMD in 2009, adds
instructions to convert between half-precision and single-precision
floating-point numbers.
It was first implemented by AMD with Bulldozer in 2011, and by Intel with Ivy
Bridge in 2012.

==== XOP
*Extended Operations (XOP)* adds new vector instructions to SSE, was first
proposed by AMD in 2015, and first implemented in Bulldozer in 2011.
XOP does not use the VEX coding scheme of AVX, instead using its own.
No Intel CPU implemented XOP, and AMD dropped support with Zen in 2017.

==== FMA
There exist two variants of *Fused Multiply-Add (FMA)*: the three-operand
*FMA3* and the four-operand *FMA4*.
The original instructions in SSE5 were three-operand DREX-encoded.
Intel's original AVX specification specified a VEX-encoded four-operand
version (FMA4).
Later, Intel changed it to a three-operand VEX-encoded version (FMA3).

AMD first implemented FMA4 with Bulldozer in 2011, and FMA3 with Piledriver in
2012.
Intel never implemented FMA4, and implemented FMA3 with Haswell in 2013.
AMD dropped official support for FMA4 with Zen in 2017.

=== AVX
*Advanced Vector Extensions (AVX)* was first proposed by Intel in 2008, and
implemented in 2011 by Intel with Sandy Bridge, and by AMD with Bulldozer.
It introduces the new _VEX instruction coding_ scheme, and expands the 128-bit
XMM SSE registers to 256-bit YMM registers (YMM0 to YMM15).
The VEX coding scheme allows three-operand operations, relaxes alignment
requirements, and allows 128-bit operations.

==== AVX2
*AVX2* is an extension to AVX introduced by Intel in 2013 with Haswell, and by
AMD in 2015 with Excavator.

==== AVX-512
*AVX-512* is a set of extensions first proposed by Intel in 2013, and first
implemented in 2015.
AVX-512 consists of multiple instruction sets, with only _AVX-512F_ (Foundation)
being mandatory.
AVX-512 expands the 256-bit AVX registers to 512-bit registers, and introduces
the new _EVEX coding scheme_, allowing for 32 registers (ZMM0 to ZMM31).
The _AVX-512VL_ (vector length) set allows the use of AVX-512 operations on
256-bit (YMM0 to YMM31) and 128-bit (XMM0 to XMM31) operands.

==== AVX-VNNI
*AVX-VNNI* allows for _AVX-512VNNI_ (virtual neural network interface)
instructions on 128-bit and 256-bit operands using the VEX encoding, for CPUs
that do not yet fully support AVX-512.

== Bit manipulation extensions
Newer x86 implementations support non-SIMD *bit manipulation instructions sets
(BMIs)*, that operate on general-purpose registers.

=== ABM
*Advanced Bit Manipulation (ABM)* consists of the instructions `popcnt` and
`lzcnt`, and was introduced by AMD with SSE4A.
Intel introduced `popcnt` as part of SSE4.2 and `lzcnt` as part of BMI1.

=== BMI1
*Bit Manipulation Instruction Set 1 (BMI1)* was introduced by AMD with
Piledriver in 2012, and implemented by Intel with Haswell in 2013.

=== TBM
*Trailing Bit Manipulation (TBM)* was introduced by AMD with Piledriver in
2012, and was never implemented by Intel.
Zen-based processors do not support TBM.

=== BMI2
*Bit Manipulation Instruction Set 2 (BMI2)* was introduced by Intel with
Haswell in 2013, and supported by AMD since Excavator in 2015.

=== ADX
*Multi-Precision Add-Carry Instruction Extensions (ADX)* is an extension
introduced by Intel with Broadwell in 2014, and supported by AMD since Zen in
2017.
It introduces instructions for the efficient adding of large integers.

== External links
* https://en.wikipedia.org/wiki/X86[x86 on Wikipedia]
